### PR TITLE
feat: add virtual property to the fields config

### PR DESCRIPTION
**Pull request by r1tsuu**
## Description

Adds `virtual` property to the fields config. Providing `true` completely disables the field in the DB, which is useful for [Virtual Fields](https://payloadcms.com/blog/learn-how-virtual-fields-can-help-solve-common-cms-challenges)
Disables abillity to query by a field with `virtual: true`.
Currently, they bloat the DB with unused tables / columns, which may as well introduce additional joins.
Discussion https://github.com/payloadcms/payload/discussions/6270
Prev PR (this one contains only this feature): https://github.com/payloadcms/payload/pull/6983

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rkingon** [comment]
+1 to this. pretty vital !

**Comment by hyusetiawan** [comment]
can't wait to drop all of these "virtual" columns im accumulating!

**Comment by joshuaja** [comment]
Can't wait for this to be merged! Thanks so much for fixing this!

**Review by DanRibbens — APPROVED** [review]

**Comment by devj3ns** [comment]
Awesome @r1tsuu! Will this feature be ported to v2 too?

**Comment by r1tsuu** [comment]
> Awesome @r1tsuu! Will this feature be ported to v2 too?

Most likely no, currently we are only fixing bugs there

**Pull request merged**
