### PR TITLE
feat: defaults bundler to vite

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

**WIP**
Goals: 
- replace dev bundler (with vite config)
- replace build bundler (with vites rollup config)

Current issues:
1. Unable to get path alias resolution working. We need vite to serve a mock module for certain paths, i.e. the import path of the bundler file within the `src/config/sanitize` file. This way the client bundle short circuits and does not attempt to import any files imported within the bundler file tree.

The gist of how this works with webpack (and should work with vite, but is not):

```ts
import path from 'path';

const mockModulePath = path.resolve(__dirname, 'relative-path-to-mock-module');
const bundlerPath = path.resolve(__dirname, 'relative-path-to-bundler');

const getBaseConfig = () => {
  return {
    // ... rest of config
    resolve: {
      alias: {
        [bundlerPath]: mockModulePath,
      },
    },
  };
};
```

- [ ] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by thgh** [comment]
You can find more mocking candidates like this: Open admin page > Chrome devtools > network tab > rightclick > copy > copy all as HAR > paste it somewhere and comb through the lines

Here are some that may not be relevant client-side.
```
compression
connect-history-api-fallback
file-type
flatley
http-status
jwt-decode
md5
path
```

**Comment by JarrodMFlesch** [comment]
@thgh for my own knowledge, what were you looking for inside the HAR file? Also what request did you download the HAR file for?

**Comment by thgh** [comment]
By clicking "Copy all as HAR", it downloads all the requests, so it's kind of a flat overview of the module tree that is being loaded. I searched for `"url":` and copied these lines to a new file. Searching for `node_modules/` or `bundler/` may be interesting too.

**Comment by JarrodMFlesch** [comment]
@thgh I wonder if we can leverage the [vite-plugin-resolve](https://github.com/vite-plugin/vite-plugin-resolve) plugin and then use the bundler path as the key and then return the mockModule in string format 🤔

**Comment by JarrodMFlesch** [comment]
I made a little progress, looks like a custom plugin makes short circuiting the bundle folder makes this relatively easy!

```ts
plugins: [
  {
    name: 'replace-bundler-path',
    transform(code, id) {
      if (id.startsWith(bundlerPath)) {
        return 'export default () => { };';
      }
      return code;
    },
  },
]
```

This works great with `yarn dev [test-folder-name]` when in core. It breaks down though when linking Payload with a project. This happens because payload's dist folder is transpiled with TSC. So I am not sure how to get that to work 🤔

**Pull request closed without merging**
