### PR TITLE
add-pino-destination-stream-support

### PR DESCRIPTION
**Pull request by dominikzogg**
## Description

I would want to control the destination of a log (in my case log to console and to a file).

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by dominikzogg** [comment]
Probably it would make sense to rename the option to `loggerDestinationStream` or `loggerDestination` or `loggerStream`. What do you think?

**Comment by denolfe** [comment]
Thanks for the PR @dominikzogg . We're planning on upgrading pino to the latest version in 2.0 (a month or so out), which will have some breaking changes for the types. I'd be curious if we could fit this in with it. Here's the PR: #2698. If you could pull it down and give your thoughts on how this would fit in, that would be great.

Overall, this seems like an easy, non-breaking change that we could get tested and merged. Can you provide an example destination stream that you were working with for writing to disk?

**Comment by dominikzogg** [comment]
@denolfe i use the same integration with a newer pino version in another project without an issue in upgrade. https://github.com/chubbyts/chubbyts-petstore/blob/master/package.json#L82 https://github.com/chubbyts/chubbyts-petstore/blob/master/src/service-factory.ts#L162

**Comment by denolfe** [comment]
@dominikzogg Fantastic, thank you.

**Comment by dominikzogg** [comment]
Hi @denolfe, is there anything missing, that i should do to finish the PR?

**Comment by denolfe** [comment]
At first glance, it's looking good. I'll review this in the coming week.

**Comment by dominikzogg** [comment]
@denolfe done, i also prefer the logger prefix, thanks for looking into it

**Comment by denolfe** [comment]
Released in https://github.com/payloadcms/payload/releases/tag/v1.11.3

**Comment by dominikzogg** [comment]
@denolfe already have it on production, thanks for mentioning!

**Pull request merged**
