### PR TITLE
feature: Allow dot-notated keys on useAsTitle when rendering relationship options

### PR DESCRIPTION
**Pull request by angelobartolome**
## Description

This fix/feature allows collections that uses dot-notation in the `useAsTitle` fields to be correctly rendered in the options when they are used in a `Relationship`

Example Collection config:
```ts
export const screens: CollectionConfig = {
  slug: "screens",
  admin: {
    useAsTitle: "metadata.screenID",
    disableDuplicate: true,
  },
// ......
```

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by jmikrut** [comment]
Hey there - this is great! Question - did you poke around to determine if this breaks anything elsewhere that we rely on `useAsTitle`? I know there are a bunch of spots that may be impacted. I'd try and search the Payload `/src/admin` folder for all instances of `useAsTitle` and then spot-check each one. 

But after that's done / confirmed, we will pull this down locally to test ourselves, and happily merge!

**Comment by angelobartolome** [comment]
Hi, yes, I tested and it works great, not breaking anything out there.

I'm writing some unit tests to validate this, got busy in my schedule but hopefully I'm able to finish this week. 

I'll also double check manually every usage, but the fix was written in a way to not break in whatever way `useAsTitle` is used

**Comment by angelobartolome** [comment]
It shouldn't be a big issue if all current unit tests + the additional ones passes right? Then I could open a new PR in the future to address those other issues

**Comment by jacobsfletch** [comment]
@angelobartolome thank you for your work here! I took a pass at this after seeing #2333 and #2334 which appear to be the same issue. PR https://github.com/payloadcms/payload/pull/2350 establishes a more permanent pattern to ensure that all instances of `useAsTitle` are standardized across the board, check it out!

**Comment by angelobartolome** [comment]
sounds perfect. thanks @jacobsfletch !

**Pull request closed without merging**
