### PR TITLE
fix: peer dependencies

### LINKED ISSUE #2564: Boiler plate app throws React error
### Link to reproduction

https://www.npmjs.com/package/create-payload-app

### To Reproduce

NOTE: This appears to only happen with npm. I know yarn is an option, but the Payload site does say that either can be used and I much prefer npm. :)

Running node 18.15.0 on Windows 11:

1. Run "npx create-payload-app"
2. Select the "blank" template.
3. Provide a mongodb connection
4. Start the server with "npm run dev"

Server should start up and successfully connect to mongodb.

### Describe the Bug

When navigating to localhost:3000/admin, the browser (Edge and Chrome) doesn't render anything and simply throws:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1465:1)
    at useReducer (react.development.js:1500:1)
    at useToastContainer (react-toastify.esm.js:251:31)
    at ToastContainer (react-toastify.esm.js:1026:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
resolveDispatcher @ react.development.js:1465
useReducer @ react.development.js:1500
useToastContainer @ react-toastify.esm.js:251
ToastContainer @ react-toastify.esm.js:1026
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

```

EDIT: as a follow up note, if you create from scratch and don't add any payload config file, it will successfully render the page and you can create an account. This is when simply setting the "dev" script to "nodemon". However, if you update the dev script to "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon" and reference a config file with collections in it, it breaks. Then, if you switch the command back to "nodemon", it still fails. This tells me that referencing the config file and creating the database collections somehow results in the error (it is a data-driven error).

### Payload Version

1.7.2

### PR DESCRIPTION
**Pull request by jacobsfletch**
## Description

Resolves all `react` version conflicts and `eslint` related peer dependency warnings. 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by DanRibbens** [comment]
I'd say fixing dependencies is not a `feat`, should be a `fix` for the changelog and semantic versioning.

I didn't uncover any other issues with this PR. I linked a project to use it with npm. Came up with a lot of warnings, but I guess that is expected:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-diff-viewer@3.1.1
npm WARN Found: react@18.2.0
npm WARN node_modules/payload/node_modules/react
npm WARN   react@"^18.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN     payload@"*" from the root project
npm WARN   21 more (@dnd-kit/core, react-dom, @dnd-kit/sortable, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.3.0 || ^16.0.0" from react-diff-viewer@3.1.1
npm WARN node_modules/payload/node_modules/react-diff-viewer
npm WARN   react-diff-viewer@"^3.1.1" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^15.3.0 || ^16.0.0" from react-diff-viewer@3.1.1
npm WARN   node_modules/payload/node_modules/react-diff-viewer
npm WARN     react-diff-viewer@"^3.1.1" from payload@1.8.2
npm WARN     node_modules/payload
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-diff-viewer@3.1.1
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/payload/node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN     payload@"*" from the root project
npm WARN   13 more (@dnd-kit/core, @faceless-ui/modal, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.3.0 || ^16.0.0" from react-diff-viewer@3.1.1
npm WARN node_modules/payload/node_modules/react-diff-viewer
npm WARN   react-diff-viewer@"^3.1.1" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^15.3.0 || ^16.0.0" from react-diff-viewer@3.1.1
npm WARN   node_modules/payload/node_modules/react-diff-viewer
npm WARN     react-diff-viewer@"^3.1.1" from payload@1.8.2
npm WARN     node_modules/payload
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-select@3.2.0
npm WARN Found: react@18.2.0
npm WARN node_modules/payload/node_modules/react
npm WARN   react@"^18.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN     payload@"*" from the root project
npm WARN   21 more (@dnd-kit/core, react-dom, @dnd-kit/sortable, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from react-select@3.2.0
npm WARN node_modules/payload/node_modules/react-select
npm WARN   react-select@"^3.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from react-select@3.2.0
npm WARN   node_modules/payload/node_modules/react-select
npm WARN     react-select@"^3.2.0" from payload@1.8.2
npm WARN     node_modules/payload
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-select@3.2.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/payload/node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN     payload@"*" from the root project
npm WARN   13 more (@dnd-kit/core, @faceless-ui/modal, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || ^17.0.0" from react-select@3.2.0
npm WARN node_modules/payload/node_modules/react-select
npm WARN   react-select@"^3.2.0" from payload@1.8.2
npm WARN   node_modules/payload
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || ^17.0.0" from react-select@3.2.0
npm WARN   node_modules/payload/node_modules/react-select
npm WARN     react-select@"^3.2.0" from payload@1.8.2
npm WARN     node_modules/payload
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

added 157 packages, and audited 159 packages in 1m

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Review by DanRibbens — APPROVED** [review]

**Comment by jacobsfletch** [comment]
I think we're in good shape here, running a quick `npm list react` show that `18.2.0` is installed at the top-level, and all dependencies that rely on it are being deduped as expected (highlighted in my screenshot):

Screenshot 2023-05-17 at 12 53 36 PM

I am going to give this one final pass from a UI perspective since the `react-select` migration _did_ effect css, but other than that this ticket is resolved.

**Comment by jacobsfletch** [comment]
And here's also a screenshot of a fresh install, there's a few warnings but nothing related to dependcies:

Screenshot 2023-05-17 at 1 01 07 PM

**Comment by jacobsfletch** [comment]
✨ 

Screenshot 2023-05-17 at 3 39 55 PM

**Pull request merged**
