### PR TITLE
fix(db-*): drizzle enums, bump drizzle-kit

### PR DESCRIPTION
**Pull request by denolfe**
- bumps drizzle-kit
- Fixes https://github.com/payloadcms/payload/issues/7492 Enum issue.

### CODE REVIEW

**Comment by digitalbase** [comment]
I think the error with enums is still there

image

**Comment by JanKups** [comment]
Can confirm the issue is occurring in `3.0.0-beta.84`

**Comment by digitalbase** [comment]
Fixed by ordering my enum in the collection config to the same order as the enum in the database

**Comment by dagim-mante** [comment]
> enum in the collection config

Can you show us the code i have been trying for hours and can't fix this.

**Comment by adameli22** [comment]
I am facing this issue in 3.0.0-beta.97

**Comment by digitalbase** [comment]
Query the database

> > enum in the collection config
> 
> Can you show us the code i have been trying for hours and can't fix this.

Query the database for that enum. Then make sure that in your collection config the values are in the exact same order. Then the error will not occur

**Pull request merged**
