### PR TITLE
chore: restricts character length in table cells

### PR DESCRIPTION
**Pull request by AlessioGr**
## Description

Old:
Screenshot 2023-11-08 at 22 23 13@2x

New:
Screenshot 2023-11-08 at 22 22 59

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](../templates/) directory (does not affect core functionality)
- [ ] Change to the [examples](../examples/) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jacobsfletch — CHANGES_REQUESTED** [review]
Have you explored a CSS-only solution for this? Such as `line-clamp` with `text-overflow: ellipse`? Check this out: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp  
Screenshot 2023-11-08 at 4 28 05 PM

**Comment by AlessioGr** [comment]
@jacobsfletch it's all CSS now - check it out again!

**Review by jacobsfletch — APPROVED** [review]

**Comment by jacobsfletch** [comment]
One last thing here, is that we might want to write an e2e test for this. It's easy for CSS to get moved and not think about the implications it might have on this specific issue. The test can be very simple though, just measure the height of a huge field to ensure its never more than x number of pixels. Then no matter how its fixed in the future, the test will ensure we never regress.

**Comment by AlessioGr** [comment]
@jacobsfletch I've added an e2e test. Might not make sense for it to be in the fields test suite, but that's exactly where you see those huge cells, so I've put it in there.

**Review by jacobsfletch — APPROVED** [review]

**Pull request merged**
