### PR TITLE
feat: configurable auto slug pluralization in the database

### LINKED ISSUE #2957: Weird Collection Name Due to Mongoose utils.toCollectionName
### Link to reproduction

https://github.com/rawkode/payload/tree/bug/pluralize

### To Reproduce

Create a `CollectionConfig` with a slug of `people`.

### Describe the Bug

Inspect the mongoDB tables and one will be called "peoples"

I tracked this down to `utils.toCollectionName` in mongoose, which in turn calls `pluralize`, available [here](https://github.com/Automattic/mongoose/blob/master/lib/helpers/pluralize.js).

This could be by-passed by providing a variable on `CollectionConfig` to specify the collection name, which would then be passed to `Schema()` via [schemaOptions](https://github.com/Automattic/mongoose/blob/d8d48458507033b24f2a66fcb43577e2d0b95c61/types/schemaoptions.d.ts#L65)

### Payload Version

1.9.5

### PR DESCRIPTION
**Pull request by AlessioGr**
Fixes #2957 

## Description

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by richadr** [comment]
- Instead of the general config, maybe it is a better idea to add this to collection config, and add an option there to control the underlying database collection/table name (allowing any name, rather than setting pluralization).
- Also, should this not come with changes to the documentation?

**Comment by AlessioGr** [comment]
> * Also, should this not come with changes to the documentation?

You're totally right, I've added those!

> Instead of the general config, maybe it is a better idea to add this to collection config, and add an option there to control the underlying database collection/table name (allowing any name, rather than setting pluralization).

So by setting pluralization to false, it should take exactly what you've provided as a slug for the database name. The reason I set it as a global option is because I didn't really see a use-case for making it a per-collection setting. Why would someone want to disable it for some collections, but enable it for others? They might as well just set it to disabled globally and manually use pluralized slugs for collections where they want it to be enabled.

One thing I'm hoping to do anyways (not decided yet) is disabling pluralization by default globally in v2.0 as well. Just makes no sense to have that in the first place, in my opinion, it's confusing if the data is saved differently than specified in the slug. Pretty unexpected behavior.

**Review by DanRibbens — CHANGES_REQUESTED** [review]
`pluralizeSlugs` we use "slug" for routing, not just mongoose collection naming. I don't think this property is the right approach.

**Comment by AlessioGr** [comment]
Closed in favor of #3153

**Pull request closed without merging**
