### PR TITLE
feat: supports RTL languages (1) - config & logic

### PR DESCRIPTION
**Pull request by ibr-hin95**
## Description

some foundation for supporting arabic and rtl languages in general, as discussed on discord.
#### [test setup](https://github.com/payloadcms/payload/commit/227d3180e03ce894acae2eb9072f8afb2ed9d396)
not that interesting, basic test env
#### [change i18n cookie name](https://github.com/payloadcms/payload/commit/5af19dcb50c7d16887623dc79a2fa4e5928836ec)
changed the i18next cookie name from i18nextLng to lng for security
#### [set html lng and dir dynamically](https://github.com/payloadcms/payload/commit/182995ffd057d8baa647fe17fdf8b7056e986027)
used the Meta component in the dashboard to set both the lang and dir html attributes dynamically from i18n
#### [arabic support](https://github.com/payloadcms/payload/commit/da05b88804fe9de2dcfd9b8b8f2074e9442143d7)
arabic translation
#### [localization optional object](https://github.com/payloadcms/payload/commit/c86a9677ec4a03a256e55b5d68a4fab79dfe1523)
- changed the localization type
```ts
\* utility to collapse keys from extended types*\
type Prettify<T> = {
  [K in keyof T]: T[K];
} & NonNullable<unknown>;

type LabeledLocale = {
  label: string;
  value: string;
  rtl?: boolean;
};

type LocalizationConfigWithNoLabels = Prettify<
  BaseLocalizationConfig & {
    locales: string[];
  }
>;

type LocalizationConfigWithLabels = Prettify<
  BaseLocalizationConfig & {
    locales: LabeledLocale[];
  }
>;

type LocalizationConfig = Prettify<
  LocalizationConfigWithNoLabels | LocalizationConfigWithLabels
>;
```
- updated the config joi schema
- then started fixing the errors in all the files affected by creating two utility functions (extractLocaleObject, unifiedLocaleConfig) and importing them so that the config is backward compatible
- added a useExtendedLocale next to the Locale in src/admin/components/utilities/Locale/index.tsx for future use

#### [optional field rtl key](https://github.com/payloadcms/payload/pull/2657/commits/e7c05f9c608ba779631233a784583a055a9b82a8)
added the option to pass a key (admin.rtl) on text inputs to override the localization default behaviour for text alignment, will be used in the scss selector later

#### [data-rtl on html field](https://github.com/payloadcms/payload/pull/2657/commits/7f96edfac57c4c3e8bef22d223a54a850c72edee)
passed the field rtl key into data attribute on the text input field for later use in scss

#### [data-rtl on html textarea](https://github.com/payloadcms/payload/pull/2657/commits/4effc8b93e3b3eb490bb05dab9e2a0c77d6f2902)
same as before but for textarea

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ibr-hin95** [comment]
it seems that someone else started on the arabic support? I'm not sure

**Comment by DanRibbens** [comment]
I merged in the ChatGPT provided Arabic translations last week. It would be good to merge yours in instead.
Is this ready for me to test?

**Comment by ibr-hin95** [comment]
> I merged in the ChatGPT provided Arabic translations last week. It would be good to merge yours in instead. Is this ready for me to test?
-----
@DanRibbens 
we just need to decide on what to do with:
1. I removed the following translation keys from ar.json and used the english ones because of some string formatting issues:
newAccountCreated
noMatchedField
titleDeleted
greaterThanMax
lessThanMin
notValidDate
I have the translation but I'm trying to fix the format
1. I'm working with @DasMergo on the css changes, should we add them here or open a different branch?

**Comment by ibr-hin95** [comment]
> I had a terrible time editing the JSON file in webstorm but was able to get it eventually how I wanted by editing in another app and copy and paste as plain text back to the IDE. I maybe said a few curse words. I'm not terribly worried about these unless there is an issue that needs to be fixed in the translations on master.
>
I pushed a fix now [fix json formatting](https://github.com/payloadcms/payload/pull/2657/commits/44a999bad3f2d9dc498360588804306d8b072f38)
> 
> I'll turn this question around. If the work here works in isolation of the CSS changes, we can split it up. If the changes in this PR make the UI unusable (or any small bugs even) we should include the CSS in the same PR. What I don't want to have happen is that this gets released and has a broken UI for RTL languages.
> 
this pr has no effect on ui at all, it just handles the foundation that the css relies on
> Does that answer your questions?
yes thank you

**Comment by DanRibbens** [comment]
Then the only thing I'd say is resolve the conflicts and I'll review and test it.

Thanks for the initiative on this work! We really appreciate all the help!

**Comment by ibr-hin95** [comment]
> Then the only thing I'd say is resolve the conflicts and I'll review and test it.
> 
> Thanks for the initiative on this work! We really appreciate all the help!

done :)

**Comment by DasMergo** [comment]
yeah @ibr-hin95 that was super. Payload is going to be first RTL Headless cms in the market  :D @DanRibbens I think this #2660 doesn't have any breaking change also for further development we make sure to not break the UI

**Comment by ibr-hin95** [comment]
Reverted the last three commits by @DasMergo  as they were committed by mistake. we agreed that all CSS changes are moved to a [different branch](https://github.com/ibr-hin95/payload/tree/rtl-scss-support)

**Comment by DanRibbens** [comment]
The build failed on your branch. Is this something you're able to reproduce and fix @ibr-hin95?
image

**Comment by ibr-hin95** [comment]
> The build failed on your branch. Is this something you're able to reproduce and fix @ibr-hin95? image

I'll try to tonight. is the build triggered manually? I'm asking so that I know how long I have to wait to be sure the build matches the results I get locally

**Comment by DanRibbens** [comment]
> I'll try to tonight. is the build triggered manually? I'm asking so that I know how long I have to wait to be sure the build matches the results I get locally

Yes, running `tsc` will fail in the first few seconds if there are any type errors which is what you're seeing in the screenshot of the CI output above.

**Comment by ibr-hin95** [comment]
> > I'll try to tonight. is the build triggered manually? I'm asking so that I know how long I have to wait to be sure the build matches the results I get locally
> 
> Yes, running `tsc` will fail in the first few seconds if there are any type errors which is what you're seeing in the screenshot of the CI output above.

done :) I'll wait for the workflow to clear

**Comment by AlessioGr** [comment]
Hi @ibr-hin95 
first of all, thank you for this amazing PR - we really want to get this merged in!

I have two questions regarding rtl in fields. Take [the Text field](https://github.com/payloadcms/payload/blob/7c259366b5a823835a968143bc535d5094c60ade/src/admin/components/forms/field-types/Text/index.tsx) as an example.
```ts
// field id rtl when current locale is rtl and admin.rtl is true also
const isRTL = (rtl && extendedLocale && extendedLocale.rtl) || false;
```

- Shouldn't we add another condition which makes sure that rtl is enabled only when the `localized` property of a field is set to true? Since, if a field isn't localized, it wouldn't be "translated" into the currently selected locale anyways. (Let me know if there's an error in my logic)
- What's the purpose of the additional admin > rtl property for fields? Wouldn't you want every text field to be RTL, if an rtl-enabled locale is currently active?

**Comment by ibr-hin95** [comment]
> * Shouldn't we add another condition which makes sure that rtl is enabled only when the `localized` property of a field is set to true? Since, if a field isn't localized, it wouldn't be "translated" into the currently selected locale anyways. (Let me know if there's an error in my logic)
>
I have to first of all make sure that we're on the same page as to what "rtl is enabled" means, in this context, it is a flag that is passed as a data attribute on the HTML element that'll signal the text alignment and will be used in the CSS rules (will be done in separate pr).
once that's been established, the only issue with your additional condition is that it assumes that more than one locale is set, and doesn't take into account the case where only one locale is set, and it happens to be an rtl locale. in that case, there's no translation happening, it's the default.
so our original intent was to use the LabeledLocale.rtl=true to signal that by default, when this locale is active, make the text alignment rtl on text fields, and you can opt-out of this by setting it to false or omitting it, and the field.admin.rtl is also to opt-out but while keeping the default that's set on the LabeledLocale.rtl level.
but now that I'm looking at it, I see a problem in my implementation, which is that since field.admin.rtl is supposed to override the default, it should be truthy by default, and only interpreted as false when it's explicitly set to false, so:
```ts
const isRTL = ((rtl !== false) && extendedLocale && extendedLocale.rtl) || false;
```
please update that on the input/textarea as I'm deep into the CSS pr :)
> * What's the purpose of the additional admin > rtl property for fields? Wouldn't you want every text field to be RTL, if an rtl-enabled locale is currently active?
>
as I explained above, no, it's used to opt-out, an example for that is phone number/uuid/email especially in a single locale set up where the only configured locale is rtl.
ps. thank you so much for your help, I tried to debug the build and fixed it so that it builds locally but the checks were still failing and I couldn't debug further as I'm overwhelmed by work atm

**Review by AlessioGr — APPROVED** [review]

**Pull request merged**
