### PR TITLE
feat(richtext-lexical)!: upgrade lexical from 0.15.0 to 0.16.0 and port over relevant playground changes

### PR DESCRIPTION
**Pull request by AlessioGr**
most notably, this scopes hr to an editor theme class, and updates some deprecated default imports to named imports

**BREAKING:**
- This upgrades the required version of lexical from 0.15.0 to 0.16.0. If you are using lexical directly in your project, possibly due to custom features, there might be breaking changes for you. Please consult the lexical 0.16.0 changelog: https://github.com/facebook/lexical/releases/tag/v0.16.0

### CODE REVIEW

**Comment by adesugbaa** [comment]
This update breaks an existing application - I have no direct usage of Lexical but I get the following errors now:

```
Failed to compile.

./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/plugins/clickableLink/index.js
Attempted import error: 'ClickableLinkPlugin' is not exported from '@lexical/react/LexicalClickableLinkPlugin.js' (imported as 'LexicalClickableLinkPlugin').

Import trace for requested module:
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/plugins/clickableLink/index.js
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/feature.client.js

./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalEditor.js
Attempted import error: 'LexicalErrorBoundary' is not exported from '@lexical/react/LexicalErrorBoundary.js' (imported as 'LexicalErrorBoundary').

Import trace for requested module:
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalEditor.js
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalProvider.js
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/Field.js
./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/index.js


> Build failed because of webpack errors
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by AlessioGr** [comment]
> This update breaks an existing application - I have no direct usage of Lexical but I get the following errors now:
> 
> ```
> Failed to compile.
> 
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/plugins/clickableLink/index.js
> Attempted import error: 'ClickableLinkPlugin' is not exported from '@lexical/react/LexicalClickableLinkPlugin.js' (imported as 'LexicalClickableLinkPlugin').
> 
> Import trace for requested module:
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/plugins/clickableLink/index.js
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/features/link/feature.client.js
> 
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalEditor.js
> Attempted import error: 'LexicalErrorBoundary' is not exported from '@lexical/react/LexicalErrorBoundary.js' (imported as 'LexicalErrorBoundary').
> 
> Import trace for requested module:
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalEditor.js
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/lexical/LexicalProvider.js
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/Field.js
> ./node_modules/.pnpm/@payloadcms+richtext-lexical@3.0.0-beta.41_@faceless-ui+modal@2.1.0-rc.0_react-dom@19.0.0-rc-_aensen6ah62gcmeiw3m33lbnlq/node_modules/@payloadcms/richtext-lexical/dist/field/index.js
> 
> 
> > Build failed because of webpack errors
>  ELIFECYCLE  Command failed with exit code 1.
> ```

Can you share your package.json?

**Comment by adesugbaa** [comment]
[package.json](https://github.com/user-attachments/files/15667291/package.json)

I updated to the rc versions of @faceless-ui when I started having this build issue.

**Comment by AlessioGr** [comment]
@adesugbaa I'm not able to reproduce this. Could you open a new issue with a reproduction? Have tested this with your exact package.json and pnpm 9.2.0

Perhaps a re-install will help. Also try running `pnpm why @lexical/react` and make sure that all lexical versions displayed in the output are on 0.16.0, otherwise it will break

**Comment by adesugbaa** [comment]
Thanks for the quick response.

This is what I get:

```
Legend: production dependency, optional only, dev only

love-leads-church@0.1.0 /Users/ayorinde/Developer/Git/Others/love-leads-church

dependencies:
@payloadcms/richtext-lexical 3.0.0-beta.41
└── @lexical/react 0.14.5 peer
```

I think @payloadcms/richtext-lexical 3.0.0-beta.41 is the culprit. I deleted my whole node_modules, and still got the same result.

**Comment by AlessioGr** [comment]
> Thanks for the quick response.
> 
> This is what I get:
> 
> ```
> Legend: production dependency, optional only, dev only
> 
> love-leads-church@0.1.0 /Users/ayorinde/Developer/Git/Others/love-leads-church
> 
> dependencies:
> @payloadcms/richtext-lexical 3.0.0-beta.41
> └── @lexical/react 0.14.5 peer
> ```
> 
> I think @payloadcms/richtext-lexical 3.0.0-beta.41 is the culprit. I deleted my whole node_modules, and still got the same result.

thaaats the problem! Can you share the package.json of the installed @payloadcms/richtext-lexical package? Should be somewhere in node_modules/@payloadcms/richtext-lexical

**Comment by AlessioGr** [comment]
Also can you analyze your pnpm lockfile and check which package is requesting @lexical/react 0.14.5?

pnpm why is kinda inaccurate and sometimes just omits packages for no reason

**Comment by adesugbaa** [comment]
I deleted my pnpm lock file, and node_modules. Reinstalled, and it's all good now.

Thanks for the support.

**Pull request merged**
