### PR TITLE
fix: textarea-field only resize vertically

### PR DESCRIPTION
**Pull request by bigmistqke**
## Description

textarea fields are capable of resizing horizontally at the moment.

this causes layout issues:

afbeelding

which even become worse when resizing the window as the textarea has a fixed horizontal width after resizing.

afbeelding

this PR adds `resize: vertical` to `.field-type.textarea textarea` which solves this problem.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by bigmistqke** [comment]
mm, I don't know why the build would fail... local tests succeed.

**Comment by JarrodMFlesch** [comment]
> mm, I don't know why the build would fail... local tests succeed.

@bigmistqke you will need to merge master into your branch, there was a fix deployed last night that resolves this issue

**Comment by bigmistqke** [comment]
Ok, build still fails somehow. I will retry the PR just to see if that works...

**Comment by bigmistqke** [comment]
closing this PR since I retried the PR to fix the failing builds.

**Pull request closed without merging**
