### PR TITLE
fix: error on graphql multiple queries

### LINKED ISSUE #3605: Race condition with database transactions when multiple queries are issued through GraphQL
### Link to reproduction

https://github.com/diesieben07/payload-transactions-demo/tree/repro-graphql-multi-query

### To Reproduce

- Make sure database transactions are in use
- Create two globals, allow read access from everyone for both
- Log in to the Admin and save both globals
- Log out of the Admin (!)
- Attempt to query both globals in one GraphQL query

The above repository allows you to do this easily. Simply run `docker compose up --attach payload` and you will get a running Payload instance plus a MongoDB ReplicaSet in Docker. Create a dummy user in the Admin, save the Globals and log out. Go to the GraphQL Playground and run the following query:
```gql
query test {
  Global1 {
    testText
  }
  Global2 {
    testText
  }
}
```
You will see that only one of the queries succeeds and you get an internal server error. 
The repository uses `patch-package` to add some trace logging to see where transactions are begun and committed.
I would recommend to disable Schema-Polling in the GraphQL-Playground settings to avoid spamming the logs from Schema-Introspection requests.
If you look at the logs, you will see that Payload creates _two_ transactions, but then keeps using only one of them, attempting to commit and end it twice.

### Describe the Bug

Payload Transactions are bound to the PayloadRequest object. However, multiple operations can happen during one request. This leads to a race condition, because _all_ operations will try to create and commit the transaction as well as end the session.
If you are unlucky, the "asynchronous Gods" will decide that one operation tries to commit on a session which has already been ended.
If you are a little more lucky (I guess), things will "appear to work", but you're not really getting the benefit of transactions, because not everything will or will not be committed/rolled back.

Either Payload should reliably create a new transaction for every operation or it should use one transaction for the whole request, but only actually commit it at the end.

### Payload Version

2.0.4

### Adapters and Plugins

@payloadcms/db-mongodb@1.0.3

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

fixes #3605
~Draft: This needs to also come with a way to make graphql return a partially successful response. Effectively this change is doing bad things where an error could be returned for a mutation but also in the same request commit a separate mutation.~
As it turns out, our GraphQL implmentation already returns errors and results at the same time making the response accurate to the database changes being committed or rolled back.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](../templates/) directory (does not affect core functionality)
- [ ] Change to the [examples](../examples/) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by diesieben07** [comment]
If I understand this correctly, this now runs every operation in a separate transaction. To me this kind of defeats the purpose of transactions. If two mutations are issued in one request, I would expect them to either both succeed or both fail.

**Comment by diesieben07** [comment]
Another issue I found with this approach: At the point where the resolvers run, there may already be a transactionID in the request, most likely cause for that is operations running from authentication (i.e. a `findByID` for the user), but there could be any number of things (plugins adding express middleware, etc. etc.).

In my opinion the "proper fix" for this would be to do this via an express middleware. The first thing in the middleware stack should be to start a transaction and the last step should be to commit it / roll it back. But I am unsure how to handle this when just using local operations.

**Comment by DanRibbens** [comment]
@diesieben07,

Thanks for taking the time to review, but I don't think we agree on this.

> If I understand this correctly, this now runs every operation in a separate transaction. To me this kind of defeats the purpose of transactions. If two mutations are issued in one request, I would expect them to either both succeed or both fail.

Payload's GraphQL response allows for multiple queries and mutations and the results for each can be returned independently. Why shouldn't it work this way?

> In my opinion the "proper fix" for this would be to do this via an express middleware. The first thing in the middleware stack should be to start a transaction and the last step should be to commit it / roll it back. But I am unsure how to handle this when just using local operations.

I just went down this rabbit hole and spent about half my day on it. It was not working as I wanted and I've reverted back to how I started making the change instead. When a request has middleware such as the `findByID` for login, that transaction will have finished and committed before the graphQL handler is called. Then with this change we're splitting the req out so that each query/mutation is done in isolation of one another, finally the full response is returned with data and `errors` if any.

I've added another test case for multiple transactions to describe this functionality and prevent future regressions.

**Comment by diesieben07** [comment]
> Payload's GraphQL response allows for multiple queries and mutations and the results for each can be returned independently. Why shouldn't it work this way?

After thinking about this more, I have come around to this way of doing this. This also makes my other suggestion moot, because this way _requires_ separate transactions per operation.

The only thing I am concerned about now is the null-safe operators you added in your [latest commit](https://github.com/payloadcms/payload/pull/3985/commits/5a36798bbb148eabbcdb3718fb83f41ce99ed054). How would such a situation ever occur if not for two operations racing to commit/abort the same transaction? If these null-safe operators are still necessary, then to me that means there is still a race somewhere, right?

**Comment by DanRibbens** [comment]
> The only thing I am concerned about now is the null-safe operators you added in your [latest commit](https://github.com/payloadcms/payload/pull/3985/commits/5a36798bbb148eabbcdb3718fb83f41ce99ed054). How would such a situation ever occur if not for two operations racing to commit/abort the same transaction? If these null-safe operators are still necessary, then to me that means there is still a race somewhere, right?

This is a good question. I don't know that it is necessary given the other changes. I thought I had seen somebody on Discord report an error with mongodb trying to end session, not with graphql or it was a single mutation, can't recall. I will remove them and reassess if any new issues are reported.

**Pull request merged**
