### PR TITLE
fix: ensures autosave only runs sequentially

### PR DESCRIPTION
**Pull request by jmikrut**
Previously, Autosave could trigger 2 parallel fetches where the second could outpace the first, leading to inconsistent results.

Now, we use a simple queue-based system where we can push multiple autosave events into a queue, and only the latest autosave will be performed.

This also prevents multiple autosaves from ever running in parallel.

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
What is the reasoning for allowing multiple queued autosaves to run? Why not just use the latest autosave?

**Comment by paulpopus** [comment]
> What is the reasoning for allowing multiple queued autosaves to run? Why not just use the latest autosave and clear the queue after it completes?

That's currently what it does here, runs only the latest and then clears the queue. It runs with a `finally` so that we can catch any new items in the queue added while the current action is being processed

```
const latestAction = queueRef.current[queueRef.current.length - 1]
queueRef.current = []
```

**Comment by JarrodMFlesch** [comment]
@paulpopus Ah yes missed that, looks good! No useEffect, I love that.

**Comment by paulpopus** [comment]
> @paulpopus Ah yes missed that, looks good! No useEffect, I love that.

"Jarrod will love this" was literally said

**Pull request merged**
