### PR TITLE
feat(ImagePreview): add sizes quick preview

### PR DESCRIPTION
**Pull request by JosefBredereck**
## Description

Adding a quick preview for all the created image sizes.
This can be useful if you are uncertain if your images get correctly cropped or if you need to adjust the crop position or the fitting property.

|First start (lesser requests) if not needed |After toggle via "eye" button|
|---|---|
|grafik |grafik|

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by qbeauperin** [comment]
This is cool! 
It looks like the perfect opportunity to store the preview state (show/hide previews) in the [user's preferences](https://payloadcms.com/docs/admin/preferences) though. 😊 
(ie: click to show once, previews always show even when changing doc until I click to hide again).

**Comment by JosefBredereck** [comment]
> This is cool! 🔥 It looks like the perfect opportunity to store the preview state (show/hide previews) in the [user's preferences](https://payloadcms.com/docs/admin/preferences) though. 😊 (ie: click to show once, previews always show even when changing doc until I click to hide again).

Isn't it that CDNs sometimes get paid by the traffic? Therefore, I tried to avoid showing it all the time.

**Comment by jmikrut** [comment]
Hey @JosefBredereck — this is a great feature, and we definitely want to get this merged into core. The only thing is that we are adding some additional functionality to this component, including focal point selection and cropping controls, which will have some overlap in the way that we "preview" the image sizes that are generated. We likely will be utilizing our drawer pattern for this type of thing.

All this being said, we'd like to provide some design intent around this feature before further work / merge. Does that make sense?

**Comment by JosefBredereck** [comment]
Yes, absolutely. Everything you listet sounds absolutely awesome.

**Comment by denolfe** [comment]
Thank you for the work here @JosefBredereck. This served as an inspiration for us to rework this interface.

We've just released 2.0 which completely revamped the upload UI and added the features here in addition to focal point selection.

The [2.0 blog post](https://payloadcms.com/blog/payload-2-0) has details on it.

**Pull request closed without merging**
