### PR TITLE
fix: defaultValues computed on new globals

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

This change makes it so that when a field has `defaultValue` set it will be returned on globals even before the document has been created. 

This change has a side-effect, if you had a collection document that was saved prior to a `defaultValue` existing on the config, when read, the document will have the new `defaultValue` that was undefined before.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by xHomu** [comment]
This seems to cause default value to trigger on read. Is that intended?

**Comment by DanRibbens** [comment]
@xHomu only when a value is not already present in the database. Is this causing an issue for you?

**Comment by xHomu** [comment]
I'll try to narrow down the exact scenario and try to create a reproduction.

**Comment by xHomu** [comment]
`defaultValue: ({user}) => user.id` would trigger an `id not found` error on read. I was able to fix it by simply change it to `user?.id`.

**Pull request merged**
