### PR TITLE
feat: add support for managing database transactions

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

https://github.com/payloadcms/payload/discussions/1487

What I've done is 
1. Make all Payload  operations use the `req.session` if it is defined.
2. Add mongoose connection to `payload.mongoConnection` allowing access to management of sessions and transactions.

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by dawidmachon** [comment]
Any chance both will go live soon?
#2076

**Comment by teunmooij** [comment]
Might be nice to expose a `startTransaction` on the request that takes a callback, that provides a contexts containing the payload crud functions and implicitely uses the transaction and does automatic commit on completion / rollback on error. If users need more power they can still use your `payload.mongoConnection` property and explicitely pass in the session into the global payload instance.

This might look something like:
```ts
type TransactionContext<TCollections> = {
  create: <T extends keyof TCollections>(options: Omit<CreateOptions<T>, 'session'>) => Promise<TCollections[T]>;
  // other functions here
};

const startTransaction = async <TCollections>(callback: (context: TransactionContext<TCollections>) => Promise<void>) => {
  const session = await payload.mongooseConnection.startSession();
  const context: TransactionContext<TCollections> = {
    create: (options) => payload.create({ ...options, session });
    // other functions here
  };

  await session.withTransaction(() => callback(context));
  session.endSession();
};
```

Which can then be used like:

```ts
const handler = async (req, res) => {
  await req.startTransaction(async transactionContext => {
    await transactionContext.create({ collection: '...', data: { ... } });
    // more crud actions here
  });
}
```

**Comment by dawidmachon** [comment]
I also was thinking of implementing an additional layer on LocalApi in Payload for rolling back or chaining 'requests' similar to promises and waiting for success execution on each. Maybe it would be easier than direct transactions in mongoose.

**Comment by DanRibbens** [comment]
This work is being taken up in the database adapter work, closing PR.

**Pull request closed without merging**
