### PR TITLE
Improve Endpoint.method type

### PR DESCRIPTION
**Pull request by AlessioGr**
I've removed the `| string` part, because

A) It breaks suggestions in the editor
B) Having any other string than the specified ones causes a `1: "endpoints[0].method" must be one of [get, head, post, put, patch, delete, connect, options]` validation error anyways

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
I think this is a fine change. @jmikrut any objections?

**Comment by AlessioGr** [comment]
Just noticed that for some reason, this fails to build. I can't really figure out why

**Comment by AlessioGr** [comment]
Nvm fixed it! Typescript just needed some more hand-holding by adding an `as Endpoint[]` here:

CleanShot 2023-01-17 at 02 43 48@2x

The same thing in the collections buildEndpoints file is done differently:
image

Here, it uses the `concat` method instead of `...`

Should the globals buildEndpoints file be adjusted to use the concat method - to be consistent? Or the other way (use ... in order to be able to leave endpoints as a `const`)?

**Comment by JarrodMFlesch** [comment]
Hey @AlessioGr just catching back up here. I think we should use push in both cases for consistency, we can actually drop the spread operator and the array around the items, push allows for pushing many things at 1 time. They just have to be separated by commas. Not sure if you will need the `as Endpoint` still, but possible.

**Comment by AlessioGr** [comment]
@JarrodMFlesch done! Everything should use .push() now

**Comment by denolfe** [comment]
@AlessioGr Plan on revisiting this one?

**Comment by AlessioGr** [comment]
> @AlessioGr Plan on revisiting this one?

@denolfe 

I think this is ready, isn't it?

**Comment by AlessioGr** [comment]
Hmm, weird, this one test is failing. Lemme check if this is just a flaky test or if I broke something.

**Comment by AlessioGr** [comment]
Very, very strange. Locally, the e2e tests seem to just hang and not even start in the first place. Will need to look into this further

**Comment by AlessioGr** [comment]
Maybe the last line uses concat as to not mutate the original variable & returns a new variable, while the push version mutates the original endpoints variable?
Why would mutating it for these specific endpoints it's adding cause any issues then, though?

**Comment by denolfe** [comment]
@AlessioGr With `push` you can only do one at a time, whereas `concat` accepts an array of items. Could this be your issue?

**Comment by AlessioGr** [comment]
> @AlessioGr With `push` you can only do one at a time, whereas `concat` accepts an array of items. Could this be your issue?

Hm, push does accept multiple values, though. It might differ when it comes to _how_ it adds the values to the array - but the end result should be the same, shouldn't it?
The only difference I'm seeing is that concat here does not mutate the original value, as it's returning the concatenation directly without modifying the original value with it.

I've pushed a commit which fixes this, by using concat there. The tests are also now passing locally! Would still love to add a comment to the code explaining why to use concat there though, but I still don't understand why

**Comment by JarrodMFlesch** [comment]
It must have had to do with mutating endpoints on the collection object, but I am not sure why. So I went ahead and copied the incoming endpoint array, then did the same for globals so they match. After tests pass we can merge it in 👍

**Pull request merged**
