### PR TITLE
chore: translate checkbox result in collection list view

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

Closes [#169](https://github.com/payloadcms/payload-3.0-demo/issues/169) from `payload-3.0-demo`.

Adds `true` and `false` translations for the checkbox field result in the collection view.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Chore (non-breaking change which does not add functionality)

## Checklist:

- [X] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
@JessChowdhury what does it display if the bool is undefined? i.e. a field without a default value?

**Comment by JessChowdhury** [comment]
> @JessChowdhury what does it display if the bool is undefined? i.e. a field without a default value?

Screenshot 2024-05-03 at 2 44 12 PM


It should show `<No {label}>` as it did does in 2.0. 

However, it got broken in 3.0 [here](https://github.com/payloadcms/payload/blob/83526da4c68f3682d9cbf9ec411199bbd590c6d2/packages/ui/src/elements/Table/DefaultCell/index.tsx#L96) - we previously had `if(!CellComponent)` and have since added `if(!CellComponent && defaultComponent)`. I just pushed another change to fix this.

**Comment by JessChowdhury** [comment]
@JarrodMFlesch the last commit [here](https://github.com/payloadcms/payload/pull/6165/commits/83526da4c68f3682d9cbf9ec411199bbd590c6d2) will also fix [this issue](https://github.com/payloadcms/payload-3.0-demo/issues/174) on the 3.0 demo repo.

**Comment by JarrodMFlesch** [comment]
Looks good, thanks!

**Pull request merged**
