### PR TITLE
fix: implement the same word boundary search as the like query

### LINKED ISSUE #1037: Relationship field word boundary search
# Bug Report

The Relationship fields uses an internal cache of documents retrieved from the API and then filters this using `react-select`'s `isSearchable` functionality. This causes a mismatch between results received from the API and the filter of said results via `isSearchable`. The reason for this is that Payload uses a word boundary search as developed in: https://github.com/payloadcms/payload/commit/ec91757257ed062c7743fca3d07d1b6af21cacb4. On the other hand the `isSearchable` filters the results on an exact match.

Take the following search query for example:
`Daily Doube 10`

Will retrieve docs from Payload with names like:
`DAILY DOUBLE #10! Opnieuw doelpuntenfestijn in de Keuken Kampioen Divisie!`
`DAILY DOUBLE #37! Ruim 2.10 keer je inzet met KKD en Championship voetbal!`

Those are then filtered out by `react-select` because they don't match the exact string entered.

## Expected Behavior

Both payload and the Relationship field in the CMS filter docs using word boundaries

## Possible Solution

See pull request (about to be opened)

### PR DESCRIPTION
**Pull request by wezzle**
## Description

Fixes #1037 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DanRibbens — APPROVED** [review]
This is a fantastic addition!

The only change I would make is to export the regex in one place that is being used in the filterOption of the Relationship field in your changes and in the src\mongoose\sanitizeFormattedValue.ts like operation. Do you want to do this? If not we'll take care of it while we're doing more testing.

A reach goal would be to add an e2e to cover the enhancement too, but this would be kind of complicated to do.

Thanks!

**Comment by wezzle** [comment]
I've refactored the regex into a separate file in the `src/utilities` folder. Let me know if this is the correct location.

I'll try and take a stab at the e2e testing as well.

**Comment by wezzle** [comment]
@DanRibbens I've add the e2e test for word boundary search (and search in general).

While doing so I noticed a few issues that I've also fixed:
- When the collection doesn't have a `useAsTitle` the default `id` field is used. The sanitizeFormattedValue then just does a normal like search, no word boundaries. I've implemented a similar check. As a relationship can be `isMulti` you could theoretically mix one `id` and one other field in the same react-select. In this case I've opted to go with word boundary search in case one of the relationships has a `useAsTitle`. I figured being able to partially match an id would not be a use-case often encountered.
- The docs on `react-select` specify `null` is a valid value for `filterOption` but that just leads to the search not working at all. I've changed it to `undefined` which does result in the expected functionality

Let me know if there's anything you'd like to see changed.

**Review by DanRibbens — APPROVED** [review]

**Comment by DanRibbens** [comment]
Thanks @wezzle, everything looks great! We'll get it out soon in the next release.

**Pull request merged**
