### PR TITLE
feat(db-postgres): Add multiple field sort by string

### PR DESCRIPTION
**Pull request by SimYunSup**
## Description

Related disscusion is #2089. For 1.x PR, #3236.

I added conditional logic for multiple field sort. sort string is implemented as comma format like [PR comment](https://github.com/payloadcms/payload/pull/3236#issuecomment-2067901468).

https://github.com/payloadcms/payload/blob/45b3f06e1b239623a8be5f73e0324aabccf244d6/packages/db-postgres/src/queries/buildQuery.ts#L98-L100

I wasn't sure what this code was doing, so I opened the PR as a draft.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by SimYunSup** [comment]
Progress: Fix adding `version.` to sortPath when queryDraft has sort.

When payload v3 is released, I hope it will be fixed and merged with the reason why `selectFields.sort` was used. :)

**Comment by max-degterev** [comment]
any chance to get this updated/merged?

**Comment by max-degterev** [comment]
guys?

**Comment by SimYunSup** [comment]
@max-degterev I'm not working on payload at the moment, so I apologize for the slow response. It will take a while for me to get back to updating this PR to the latest commit.

**Comment by r1tsuu** [comment]
This was implemented here https://github.com/payloadcms/payload/pull/8799 and will be in the next release, closing this old one, thanks for the attempt!.

**Pull request closed without merging**
