### PR TITLE
Fix ctrl s on global section

### LINKED ISSUE #3336: Cmd + S hotkey doesn't work sometimes due to `editDepth` check
### Link to reproduction

https://github.com/hdodov/payload/tree/bug-hotkeys

### To Reproduce

1. Run `yarn dev _community`
2. Change the "Menu" global
3. Hit <kbd>Cmd + S</kbd>

### Describe the Bug

As I've demonstrated in https://github.com/payloadcms/payload/pull/1821#issuecomment-1683388162, the hotkey doesn't always work:

https://github.com/payloadcms/payload/assets/5570098/b8f91b38-9b90-44a7-80c2-f16dcaf03558

After digging a bit, it appears that `maxEditDepth` differs from `editDepth` upon pressing <kbd>Cmd + S</kbd>:

image

…so this check fails:

https://github.com/payloadcms/payload/blob/6754f55ce0a09b1a765f19426ef269d09e1191c0/src/admin/hooks/useHotkey.tsx#L91-L94

The logs I've shown on the screenshot can be seen on my branch: https://github.com/hdodov/payload/tree/bug-hotkeys

As a reminder, this happens in the original Payload repo, in the `_community` playground. This is not in my own project, so I believe it's genuinely a problem with Payload.

### Payload Version

1.15.6

### PR DESCRIPTION
**Pull request by limistah**
## Description

Fixes [Issue #3336](https://github.com/payloadcms/payload/issues/3336)

- [X] I have read and understand the [CONTRIBUTING.md](../CONTRIBUTING.md) document in this repository.

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
This has been fixed on the 2.0 branch, if you want to make the same fix here we can merge that in! https://github.com/payloadcms/payload/blob/2.0/packages/payload/src/admin/components/views/Global/index.tsx#L105

Basically you just need to move the EditDepth provider up one level.

Looks like your branch needs to merge master changes in also. LMK if this makes sense!

**Comment by limistah** [comment]
Yes, it does.

I think it should be supported on here as well.

I'll make the changes.

**Comment by limistah** [comment]
Changes have been made.

**Comment by JarrodMFlesch** [comment]
Thanks @limistah! Merged 👍

**Pull request merged**
