### PR TITLE
feat: RTL Support

### PR DESCRIPTION
**Pull request by AlessioGr**
## Description

**Previous PRs:**
Logic: https://github.com/payloadcms/payload/pull/2657
CSS: https://github.com/payloadcms/payload/pull/2660

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Checklist:

- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by AlessioGr** [comment]
@DanRibbens this is ready for another review! I've incorporated your suggested changes from https://github.com/payloadcms/payload/pull/2660#issuecomment-1579182559 here.

The SanitizedConfig now has a `locales` object, which is always an object array with a value and label each. Additionally, it has a `localesSimple` object which is also populated inside the sanitize method.

**Comment by DanRibbens** [comment]
I haven't reviewed yet, what is the breaking change? 

I think we can avoid it being breaking as we can do our own sanitization of the locales if needed as I suspect that's where the breaking change is. 

We can talk about it tomorrow.

It needs to be documented in the PR description if there is a breaking change too so we can get it in the release notes.

**Comment by JarrodMFlesch** [comment]
@AlessioGr could you comment on the breaking change jus so anyone looking at this PR understands why we would push this until 2.0? Thanks!

**Comment by AlessioGr** [comment]
> @AlessioGr could you comment on the breaking change just so anyone looking at this PR understands why we would push this until 2.0?
> 
> Thanks!

@JarrodMFlesch Sure! This PR will modify the `config.localization.locales` property. It's no longer a list of locale strings, but an array of locale objects - each locale object consisting of a `value`, `label` and `rtl` property.

This will break every plugin / piece of code which uses payload's `locales` property, expecting a list of strings.

More relevant information for this decision can also be found in [this discord thread](https://discord.com/channels/967097582721572934/1102950643259424828/1130529748737609900) and [this GitHub comment](https://github.com/payloadcms/payload/pull/2660#issuecomment-1579182559).

**Comment by ibr-hin95** [comment]
@AlessioGr @DanRibbens @JarrodMFlesch 
Hello :)
I didn't receive the updates from [2660](https://github.com/payloadcms/payload/pull/2660) and was overwhelmed by work, so I'm just catching up now. and because we're building our stack at work on top of payload, I'm able to designate a dev from my team to complete this starting today (because we need the feature urgently).
now I see this pr is open, and that most of the requirements have been implemented, so: 
1) is everything done or do you have a list of tasks to be done that I can transfer to our ticket manager?
2) if it's not done but you don't have a list, should he just test it with a complete config and fix if needed?
3) I see that the logic has changed, but do we still have the same mental model?
many thanks and apologies for the late response

**Comment by DanRibbens** [comment]
Hi @ibr-hin95! We were planning to push this out in our 2.0 release because of some breaking changes. I can elaborate on this more tomorrow.

**Comment by ibr-hin95** [comment]
> Hi @ibr-hin95! We were planning to push this out in our 2.0 release because of some breaking changes. I can elaborate on this more tomorrow.

np, because of the time difference, we'll be working on testing everything today (a few hours from now :) ) and we'll wait for your response tomorrow. 
@AlessioGr we would also be happy for any input from you

**Comment by ibr-hin95** [comment]
@AlessioGr @DanRibbens 
so we (me and @muathkhatib) started testing the CSS yesterday and we're keeping track of everything in a md file [here](https://hackmd.io/@Tindo-Team/BkxB-7XEY), we write down the visual bugs in the CSS and fix them, and try to test the logic too. let us know if anything comes up

**Review by DanRibbens — APPROVED** [review]

**Comment by DanRibbens** [comment]
@ibr-hin95 and @DasMergo, if you have more work on RTL coming, please branch from and target the new [2.0 branch](https://github.com/payloadcms/payload/tree/2.0). Once 2.0 is released, you can target `main` as that will be the new default going forward.

I can't wait to announce RTL admin UI support when this is out!

We will have a blog post dedicated to this feature and we would like to mention you both as contributors. If you have any other handle besides your GitHub accounts you wish us to link, let us know. We can also link to your websites or company. And if you don't want to be mentioned for any reason, that is fine too, we can respect that.

Thank you so much for your contributions!

**Comment by ibr-hin95** [comment]
no problem, we're working on testing everything right now by testing all kinds of field types and nested fields especially to make sure everything is good.
and for the blog post, I think the gh handle is more than enough :).
btw, is there any timeline for 2.0?

**Comment by DanRibbens** [comment]
> btw, is there any timeline for 2.0?

Sept 22 maybe.

**Comment by DasMergo** [comment]
cant wait 😄

**Pull request merged**
