### PR TITLE
fix(graphql): avoid adding extra password fields when running mutations (#8032)

### PR DESCRIPTION
**Pull request by agrippa1994**
### What?
`auth` enabled collections show "Password" fields whenever a GraphQL query is performed or the GraphQL playground is opened (see #8032)

You can reproduce this behavior by spinning up the `admin` test with PostgreSQL:
```bash
pnpm dev:postgres admin
```

Open the admin UI and navigate to the `dev@payloadcms.com` document in the `Users` collection (see screenshot below)
image

Open the [GraphQL playground](http://localhost:3000/api/graphql-playground) 
Open the admin UI and select the user again. The password field appears multiple times.
Subsequent GraphQL playground page refreshes lead to even more password fields in the admin UI.

image

The current behavior has an impact during development and even on production. Since the password field is added to the collection, payload tries to add this field to the database as well (at least I could observe at in my own project)

### Why?
In the `packages/graphql/src/schema/initCollections.ts` file, the `initCollections` function mutates the config object by adding the password field for the GraphQL schema (line 128). This mutation adds the field multiple times, depending how often you open the playground. In addition, this added field is also shown in the UI since the config object is shared (see screenshot above).

### How?
By creating a deep copy of the object, the mutation of the configuration does not leak additional fields to the UI or other parts of the code.

### CODE REVIEW

**Review by paulpopus — APPROVED** [review]

**Comment by paulpopus** [comment]
Thanks for your PR here!

**Comment by agrippa1994** [comment]
Thanks for approving the PR! Could you please restart the build? As far as I can see the build has been cancelled yesterday and now I can‘t merge.

**Comment by paulpopus** [comment]
You might be able to fix it from your branch actually, can you try pushing an empty commit to retrigger it? there's no manual retriggering on my end because the job hasn't even registered

run this and push it

```
git commit -m "trigger CI" --allow-empty
```

**Comment by agrippa1994** [comment]
@paulpopus I have pushed the empty commit, could you please approve the workflow run? Thanks

**Comment by paulpopus** [comment]
Thanks, it'll be ready to merge. Before I do I wanna do a deeper dive on monday into the core issue to make sure that this is the fix and it's not something deeper in how we generate the schema

**Comment by paulpopus** [comment]
Yeah I don't think we should be copying the config like this here, it's inefficient and can lead to more bugs down the road.

Reverse your changes here and go to `/packages/graphql/src/schema/initCollections.ts` and make this change on line 127

```ts
 if (collectionConfig.auth && !collectionConfig.auth.disableLocalStrategy) {
      const existingPasswordField = fields.find(
        (field) => 'name' in field && field.name === 'password',
      )

      if (!existingPasswordField) {
        fields.push({
          name: 'password',
          type: 'text',
          label: 'Password',
          required: true,
        })
      }
    }
```

So instead of copying and discarding the config, we simply don't push a password field into it if it already exists. Test it and let me know if it works for you as well.


I'm happy to make this into a separate PR if you're short on time but I thought you might want the opportunity to get your commit credited in.

**Comment by agrippa1994** [comment]
I have tried your suggested fix before opening the PR and this does not fix the issue unfortunately. The password field will still appear in the Admin UI, however, it only appears once. 
The underlaying problem is the mutation of the shared payload config by the GraphQL schema generation. The schema generator adds the "password" field to the "fields" entry of the collection. The reference of the "fields" entry is used everywhere in the application which leaks the password field to the UI and other parts of payload.

My latest commit makes an explicit copy of the fields only instead of creating a copy of the whole config object. This avoids mutating the "fields" object reference.

**Comment by paulpopus** [comment]
Yeah you're right. Thanks again for your work and iterations here!

**Pull request merged**
