### PR TITLE
Feat: Add query support for geo within and intersects

### PR DESCRIPTION
**Pull request by lablancas**
## Description

2 new query operators have been added:
- `within` adds support for MongoDB [$geoWithin](https://www.mongodb.com/docs/manual/reference/operator/query/geoWithin/)
- `intersects` adds support for MongoDB [$geoIntersects](https://www.mongodb.com/docs/manual/reference/operator/query/geoIntersects/)

Both new operators are similar to [near](https://payloadcms.com/docs/fields/point#querying) functionality that is already available.

### Example Usage
Setup for examples below
```
import { CollectionConfig } from "payload/types";

const Points : CollectionConfig = {
  slug: "points",
  fields: [
    {
      name: "name",
      type: "text",
    },
    {
      name: "point",
      type: "json",
    },
  ],
};

// sample point created
payload.create({
  collection: Points.slug,
  data: {
    name: "Point 1",
    point: {
      type: "Point",
      coordinates: [0.5, 0.5],
    },
  },
});

const polygon = {
    type: "Polygon",
    coordinates: [[
        [0.0, 0.0],
        [1.0, 1.0],
        [1.0, 0.0],
        [0.0, 0.0],
    ]],
}
```

Example usage for `within`
```
payload.find({
    collection: Points.slug,
    where: {
        point: {
          within: polygon,
        },
    },
});
```

Example usage for `intersects`
```
payload.find({
    collection: Points.slug,
    where: {
        point: {
          intersects: polygon,
        },
    },
});

```

### Disclaimers
I have allowed both of these operators to work with JSON field types; however, the user must ensure the JSON is a valid geospatial data object.

The `polygon` variable is passed to MongoDB as the `$geometry` object for both `$geoWithin` and `$geoIntersects` queries; therefore, the input value must be a valid GeoJSON object type.

Need to discuss with Payload development team to determine 
- if/how to handle validating the field and input value when one of these new operators is used, and
- should we allow JSON to use these new query operators or add a new Polygon field type

As of commit [e685694](https://github.com/payloadcms/payload/commit/e685694a50f1fb6ad36f0efff9e333e51180b390), a MongoDB error is thrown if 
- the query does not have a valid geospatial data field, or 
- the query does not have a valid GeoJSON object input value

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by lablancas** [comment]
I can update documentation and add test cases once I know if I need to make more changes to the code in this pull request.

**Comment by lablancas** [comment]
I will not pause code pushes so that more builds are not added to the queue. Feel free to build only the last commit.

**Comment by DanRibbens** [comment]
Hey @lablancas, thanks for the contribution!

I can review the changes now if you're done?

When you add your tests, I would start by copying what you already put in your example usage above and adding it to the point field tests found here:

https://github.com/payloadcms/payload/blob/f84b4323e2fce57e2e14b181e486ed72cc09ded5/test/fields/int.spec.ts#L339

If you see how I did the `near` field, we want to make sure coverage has both positive and negative search results (no false positives).

Appreciate the help!

**Comment by lablancas** [comment]
Hey @DanRibbens , I am done for today. 

As I was reviewing the generated GraphQL schema, I saw that it was setting the input type for these query operators as `[Float]` which is the GraphQL schema for a point. I changed the input type to JSON to fix this. This means is that you cannot use within or intersects on a point field type. 

Do you have any concerns with that?

**Comment by DanRibbens** [comment]
Changing JSON is less prescriptive so that isn't ideal. It could also be debated that this is a breaking change for people relying on the schema generation for their projects. 

Can you think of any other ways besides using JSON to get this done? I want to be sure we've explored our options before accepting this change.

This comment in this thread is interesting: https://github.com/graphql/graphql-spec/issues/534#issuecomment-876573911. I'd have to research this more and how we can work it into our existing GraphQL implementation. I wonder if we could add the operator specific types for the where query inputs just for `within` and `intersects` for the point field.

**Comment by lablancas** [comment]
Hi @DanRibbens, Ideally, we would want to have GraphQL schema types for all the GeoJSON object types. I am only concerned with Point and Polygon, but others may be interested in more than that. 

I did figure out how to add a GeoJSON Polygon type and input to the GraphQL schema; however, it was not a scalar like that thread suggested. I could post that as a pull request so you can see it. The pattern could be expanded to handle other GeoJSON object types or maybe even to convert `coordinates` into scalars.

To make it even more complicated, the `within` and `intersects` query can be used with a mixture of the GeoJSON object types. 

For example, you can query 
- a Point within a Polygon, 
- a Polygon within a Polygon, 
- a Polygon intersecting with a Point, 
- a Point intersecting with a Polygon, 
- a Polygon intersecting with a Polygon,
- and several other combinations of other GeoJSON object types.

Ideally, we would want to make the input type for the within and intersects operations a GraphQL Union of the possible GeoJSON Object types; however, I have not figure out how to implement that yet.

**Comment by lablancas** [comment]
@DanRibbens Seems like GraphQL does not support interface union types for inputs so that makes things a little difficult. Wondering if it makes sense to use a GeoJSON interface for the GraphQL object type which only supports Point and Polygon to start. Then create operators for `withinPoint`, `withinPolygon`, `intersectsPoint`, and `intersectsPolygon`

This would allow GeoJSON types to use these operators, but you would have to pick the operator that matches the input type. What do you think about this? Or do you have some other ideas I should consider?

**Comment by AlessioGr** [comment]
@lablancas I've just opened a PR targeting this PR branch here: https://github.com/lineups-io/payload/pull/4 (sorry for the commit mess - the update from master messed it up a bit. Check out the latest commits manually to see my actual changes).

What I did was define a type which would work for all GeoJSON Objects:

```ts
const GeoJSONObject = new GraphQLInputObjectType({
  name: 'GeoJSONObject',
  fields: {
    type: { type: GraphQLString },
    coordinates: {
      type: GraphQLJSON,
    },
  },
});
```

It's a bit more specific than just using `GraphQLJSON` as the different GeoJSON objects only differ in the `coordinates` property. Not perfect, but better, since you're totally right about GraphQL not supporting union types.

@DanRibbens let me know if you think that's enough, or if you would rather have the suggested `withinPoint` / `withinPolygon` operations. I, personally, like having this more lax type, as it allows you to pass something which is more similar to what MongoDB accepts.

Plus, even if you do mess up the coordinates type, it would just throw an error:

Screenshot 2023-07-20 at 04 16 31


Additionally, GraphQL `where` operators can now have dynamic types depending on the operator, which allowed me to add `within` and `intersect` to the points field.

What do you think?

**Comment by lablancas** [comment]
Thanks @AlessioGr 

I am fine with this solution. I did go down the path of building the schema and validation for geojson polygon in [lineups-io#3](https://github.com/lineups-io/payload/pull/3), but I think your solution is way simpler.

I can pivot to this strategy pretty easily. Since this isn't a strictly defined schema, how much schema validation do we want (if any)? Do we want to restrict the geojson types? Lastly, what test cases would we want to cover since this now would support lots of geojson scenarios and even the chance for invalid coordinates?

**Comment by DanRibbens** [comment]
I'm having trouble reviewing the PR from @AlessioGr since it includes all the changes from master. We need to merge master here on this PR for that to make sense.

As for tests, I would like to see that we can have happy paths for the queries returning docs, with no false positives in integration test coverage. This should be done in both rest and graphql.

If we want to do any validation on the input, you could add that logic to src/fields/validations.ts and then test it in the validations.spec.ts file that lives next to it. I would keep the  logic as basic as possible just to help people who are completely lost. I'm indifferent as to whether we need this or not, since it is only a nice to have and could be a later improvement. Also with mongodb handling the validation already, it is really only when we go to multiple databases that this may be helpful.

Great work here!

**Comment by AlessioGr** [comment]
> I'm having trouble reviewing the PR from @AlessioGr since it includes all the changes from master. We need to merge master here on this PR for that to make sense.

@DanRibbens opened a new PR [here](https://github.com/lineups-io/payload/pull/5).

> I am fine with this solution. I did go down the path of building the schema and validation for geojson polygon in https://github.com/lineups-io/payload/pull/3, but I think your solution is way simpler.

Hm, what you did looks like it would accommodate stuff like a Polygon intersecting within a Polygon. Still relevant, as currently you'd have to use the JSON field which has no validation whatsoever. I don't know how I feel about it being a completely different field type though

**Comment by DanRibbens** [comment]
Oh yeah, I was confused about validation, ignore what I said.

**Comment by lablancas** [comment]
@DanRibbens @AlessioGr 

I've added a more generic GeoJSON type with Point and Polygon validations. We can add more validations later if we want more types or I can remove the validations if you want. 

I treated GeoJSON as an extension of the existing JSON field type when I configured it. So it has the JSON query operators plus the new within and intersects operators. Let me know if I missed anything.

I can begin working on integration and field validation test cases if ya'll think this code looks like the right solution.

**Comment by AlessioGr** [comment]
Hey @lablancas,

Thanks again for your hard work on this! I've chosen to go with #3183 since it takes from the earlier version of your contribution before the custom field types and has some of my graphQL tweaks.

We're really keen on getting the within and intersect operators in ASAP, supporting:

- a Point within a Point,
- a Point within a Polygon.

For the other GeoJSON stuff, the new field you added is just represented by the JSON field in the admin panel. It'd be cool if it had its own UI to make things easier for users. Plus, we're still debating if we need a brand new field type for it.

Given this, it'll take much longer to pull everything together, so I took the initial changes.

For what's next, how about starting a GH Discussion about a new field type for polygons or other ways to represent it in payload? Then, depending on where that goes, we can check back on this PR or kick off a new one.

**Pull request closed without merging**
