### PR TITLE
fix(db-postgres): drafts cannot be saved because not null constraint

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

`required` fields inside of a collection with `versions.drafts` enabled were failing to save because of `not null` constraints added to the table columns.

- [x] I have read and understand the [CONTRIBUTING.md](../CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by mattddean** [comment]
I see the problem, but this one is hard to look at :). Would you ever consider rethinking how drafts work with multiplayer editing on the roadmap? Theoretically, a different data structure will be required to support multiplayer editing, and that data structure could solve for the requirement to save in-progress and incomplete documents, leaving drafts to store complete but unpublished documents.

I also think that the necessity to save incomplete documents is lessened with the live preview feature.

It feels unexpected that being able to unpublish documents kills full-stack required field types, especially now that fully typed databases are supported.

**Comment by DanRibbens** [comment]
Appreciate the feedback @mattddean, 
I did consider if it would be better to just throw draft content into a JSON column in the database, but I think that is the opposite direction you're advocating for. 

With multiplayer editing we're likely going to have a websocket open with a continuously updating state writing to the database similar to how `versions.drafts.autosave` currently works over REST. I actually think what we're doing with `not null` is a prerequisite for multiplayer editing. 

We're open to ideas on the best way forward, how else would you suggest we model the data?

**Comment by mattddean** [comment]
The JSON field idea went through my head too. What if we used a JSON field to store the multiplayer editing state and required that in order to create the first draft, all of the fields are filled out? As changes are made in a multiplayer format, we'd persist them in a JSON field and then apply them to the document when a user clicks Save Draft or Publish.

This would have the side effect of allowing multiplayer editing for non-draft-enabled collections, since the multiplayer state would be completely separate.

**Comment by stevekuznetsov** [comment]
> It feels unexpected that being able to unpublish documents kills full-stack required field types, especially now that fully typed databases are supported.

@DanRibbens  @mattddean  this just bit us in production - and as noted above, it's very surprising! While flipping a published bit in a table is an ergonomic & cheap way to publish/unpublish/draft a document, coming at the cost of no longer making required fields truly required is more than a bit terrifying. A separate sister table with no constraints might be another approach, or a single table with NOT NULL constraints and some sentinel values that the UI could use to add placeholders for missing-but-required fields in a saved draft.

I don't know to what extent it's even possible to rethink a decision _this_ fundamental to the schema (or how hairy the data migrations would be) but it seems like a real shame to lose constraints for users with a relational database.

**Pull request merged**
