### PR TITLE
New RichText Editor based on Lexical

### PR DESCRIPTION
**Pull request by AlessioGr**
## Images
Dark mode

Light mode

## Description

This adds a new lexicalRichText component (without replacing the original richText component yet). I've already added it to test/fields if you want to test it out.

[Lexical](https://github.com/facebook/lexical) is Metas new rich text editor which should replace Draft.js. In fact, it seems like Meta is already using it in production (correct me if I'm wrong).

The main reason for the change is DX. Lexical is a LOT easier to customize compared to other libraries like Slate or TipTap. Adding this to Payload could thus bring HUGE value to users trying to customize their rich text editor (which is pretty much the most important component in Payload) and would be great future-proofing.
It's also platform-agnostic which also brings a lot of benefits (I can now easily send content from my Svelte backend which uses Lexical to Payload).
I'm sure it also has a lot of other benefits outside of DX - feel free to research a bit more!

This PR currently pretty much started with _most_ of Lexical's [Playground](https://playground.lexical.dev/) (code [here](https://github.com/facebook/lexical/tree/main/packages/lexical-playground)) being copied. I extended on top of that.

By default, it can even do comments & collaborative editing, but I've removed that functionality to get an initial version to work. This can be added later on.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by AlessioGr** [comment]
Would need to know what direction to take this, as I'd like to put some work in to get it merged!

Should this stay a separate component (LexicalRichText), or be merged into the existing richtext component? (if yes, how? How should the individual props be separated?)

**Comment by JarrodMFlesch** [comment]
Personally first I would like to have this trimmed down, to a more basic implementation. That alone will make this PR consumable for a review standpoint. It might be nice to see the Lexical RichText editor with a couple (1-3) different types of elements/leaves (H1, underline, link).

From there the api will be easier to digest and easier for maintainers think about side-affects (how will we handle relationships, extensibility, etc) before thinking about it's adoption into the core. I _do_ think this is very cool, just difficult to consume in its current state.

Thoughts?

**Comment by AlessioGr** [comment]
> Personally first I would like to have this trimmed down, to a more basic implementation. That alone will make this PR consumable for a review standpoint. It might be nice to see the Lexical RichText editor with a couple (1-3) different types of elements/leaves (H1, underline, link).

So each of these is basically a plugin. **Would it be enough to just disable the plugin (one line) but leave the implementation there?** Also I wanna note that 99% of the implementation has been done by Meta, so there shouldn't be a ton of surprises in the review. If we keep it similar to Meta's implementation, it'll be easier to upstream future changes.

**Comment by AlessioGr** [comment]
I've cleaned it up to the point where all the useless or buggy stuff is gone. Anything else in it I'd consider useful. Dark mode should now also work in most places - even tweets.

> From there the api will be easier to digest and easier for maintainers think about side-affects (how will we handle relationships, extensibility, etc) before thinking about it's adoption into the core. I do think this is very cool, just difficult to consume in its current state.

I think, given how the code is structured, the extra features shouldn't get in the way of things like relationships and extensibility, should it?
From what I see, relationships would just be an addition to the link plugin, as well as a plugin of its own.
As for extensibility, we'd pretty much just need to give users the ability to insert plugins as props to where the others are inserted, as well as edit the toolbar, which shouldn't be too hard to do. Given how separated the features are, I don't see how they could disturb that.

Reviewing the existing code would take longer, but given that it's been mostly provided by Meta & not me, we can be more lenient there.
In the end, starting out with that feature-set, should be a huge time saver. Plus they're all super modular

**Comment by jmikrut** [comment]
Hey @AlessioGr — you are really putting in the work here! This is awesome to see. Just an FYI - the team and I will get together this week to review this work and determine how it should work alongside of our existing Slate implementation / which features are missing / etc.

Great stuff though. We're pumped.

**Comment by AlessioGr** [comment]
> Hey @AlessioGr — you are really putting in the work here! This is awesome to see. Just an FYI - the team and I will get together this week to review this work and determine how it should work alongside of our existing Slate implementation / which features are missing / etc.
> 
> Great stuff though. We're pumped.

Hey, thank you for your reply! Really happy to hear it's getting looked at! As you can see, I'm trying to keep some momentum with my commits to get it implemented/done, as I'm really keen on starting new projects with the lexical editor rather than the old one 😀

Here's a quick progress report so far:

- **Preview** of the rich text  (convert to plain text & display in the collection) is working perfectly. Might be great checking out the performance of it though, as I'm using a headless lexical editor to convert it to plain text.
- Light & dark mode / **styling** is done. However, it still has some smaller inconsistencies here and there which could be improved.
- **Images/uploads**: I have implemented the same upload modal which is being used in the slate editor, and it's working great so far! Issues/questions:
  - Should images be resizable? (they currently are)
  - Custom fields support for images needs to be added, as well as the edit modal
  - Fields which are outputted as json need to be checked. Which objects do we need outputted additionally and which objects can we scrap?
- **Links**. I have re-done the link element/plugin, so the link add/edit modal reflects what's being used in the Slate editor. It's currently working for both URLs and internal document linking already! Issues/questions left:
  - Again, custom fields (like a rel= field).
  - The doc is outputted in the json correctly. However, it's not populated. Would be great if you could specifically look into that, as I'm not sure how to control if or if it shouldn't be populated
- **Validation** of the lexicalRichText field itself needs to be looked at. I don't think I did that properly
- Overall **extensibility** should be looked at. Shouldn't be too hard, we basically need to let the user inject stuff into the toolbar, as well as the LexicalRichText.tsx to add their plugin. Apart from the general editor, links & upload fields should be made extensible as well.
- As you said "determine how it should work alongside of our existing Slate implementation"
- Add a "relationship" element similar to the slate editor. Doesn't need to be in the initial "release" though as it can always be added later without breaking the data.

Hope that helps!

**Comment by AlessioGr** [comment]
Thank you, moving it over to plugin format works really well! I've just finished populating data for internal links & uploads as well - working great! https://github.com/AlessioGr/payload-plugin-lexical/blob/master/src/fields/LexicalRichText/index.tsx#L79

I was unable to properly make the plugin installable via npm, or get modals in the demo to work, so would be great if you could look into that, as I've given up on that part.

Currently just copying over the plugin source into my project - that's working without issues at least.

**Comment by jacobsfletch** [comment]
@AlessioGr it sounds like you're well on your way. I'm going to close this PR since we have no plans to merge it in, but let's continue the discussion in Discord. It's been super cool to track your progress there.

For anyone just jumping into this conversation, @AlessioGr is building this as a plugin. Check it out: https://github.com/AlessioGr/payload-plugin-lexical

**Comment by SalahAdDin** [comment]
> @AlessioGr it sounds like you're well on your way. I'm going to close this PR since we have no plans to merge it in, but let's continue the discussion in Discord. It's been super cool to track your progress there.
> 
> For anyone just jumping into this conversation, @AlessioGr is building this as a plugin. Check it out: https://github.com/AlessioGr/payload-plugin-lexical

We need a Tiptap one.

**Pull request closed without merging**
