### PR TITLE
feat: relationship field: open in new tab button

### PR DESCRIPTION
**Pull request by AlessioGr**
## Description

This PR
1. adds the ability to use the Edit button in the relationship field even if it's read-only, by overriding the parent's pointer events
2. Adds a new "Open" button next to the edit button which opens the referenced document in a new tab

## Showcase

https://user-images.githubusercontent.com/70709113/211009068-2a0da459-aef9-4a18-bdc6-d901f3deec33.mov

## What still needs to be done

- [ ] Use a different SVG for the "Open" icon, to match the padding of the other buttons. [This](https://icon-sets.iconify.design/material-symbols/open-in-new-sharp/) is the current one I'm using temporarily. I don't know where you're getting the current Icons from / how you're creating them, so would be great if you can handle that.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by AlessioGr** [comment]
Not sure why the tests are failing here - it's working for me locally

**Comment by jacobsfletch** [comment]
@AlessioGr much needed! First impressions here are the UI is getting too button-heavy. My initial ideas here were to allow the drawer to open, and display the backlink _there_ instead of directly in the field. Maybe we wrap the displayed `id` in the drawer with a link.

**Comment by AlessioGr** [comment]
> @AlessioGr much needed! First impressions here are the UI is getting too button-heavy
I think it's still "okay" with these two buttons but I did have that worry too, yeah.

> My initial ideas here were to allow the drawer to open, and display the backlink there instead of directly in the field
That could work, but I think that would waste too much time, as it needs 2 clicks instead of one.

> Maybe we wrap the displayed id in the drawer with a link.
That was my personal initial thought, but how would you handle hasMany relationships then, as you're able to hold those to change their order? Let the padding handle the dragging and the ID the link maybe?

**Comment by jacobsfletch** [comment]
> That could work, but I think that would waste too much time, as it needs 2 clicks instead of one.

But with the drawer UI, you shouldn't typically need to perform that extra click. You simply make your edits directly on screen.

> Maybe we wrap the displayed id in the drawer with a link.

What I meant by this is to wrap the id that is shown _in the drawer_ after it's opened. Not in the relationship field, you're spot on in that the drag handler would get in the way.

**Comment by iakshay** [comment]
> @AlessioGr much needed! First impressions here are the UI is getting too button-heavy. 

Feel the same, and click areas are also tiny. Thinking if we could use the the array field UI here? We could then have regular style buttons.

P.S - Doesn't need to happen in this PR.

**Comment by AlessioGr** [comment]
@jacobsfletch 
> But with the drawer UI, you shouldn't typically need to perform that extra click. You simply make your edits directly on screen.

The drawer UI is great for that, yep! But being able to open it directly is great - for the same reason as to why your web browser doesn't open all internal links in a drawer, but lets you open it in a new page. I often want to open multiple relationships at the same time in a new tab for whatever reason - often because I want to edit them later and have them saved in a browser tab. Maybe I wanna put the links to them in my notes to edit them later. Or put them on my second monitor and have both visible at the same time. Definitely important to be able to open them up in a new page quickly.

If that was IN the drawer, I'd need 2 clicks to be able to open them in a new tab, which isn't as efficient and a little annoying.

BUT I found a pretty creative solution:

https://user-images.githubusercontent.com/70709113/211064356-6b8b35b8-7cfe-4a1c-9e33-2abe8746f1f0.mov

Great huh? 
#1 Dragging them is a way less common scenario than wanting to open the actual link to the document. So now it's a small drag icon on the left which you can hold to drag them
#2 This icon also implies that you are able to drag those blocks in the first place! With the old design I actually didn't know for a while that you're able to drag those in the first place. This makes it pretty clear!

What do you think?

**Comment by jacobsfletch** [comment]
@AlessioGr that makes perfect sense and I think your solution is great!

**Comment by AlessioGr** [comment]
Just found Payload already has a Drag icon included. Here's how that looks:
image

**Comment by AlessioGr** [comment]
> @AlessioGr that makes perfect sense and I think your solution is great!

Perfect, just pushed the changes :)

**Comment by jacobsfletch** [comment]
@AlessioGr I'll get this reviewed, good work and thank you!

**Comment by AlessioGr** [comment]
> @AlessioGr I'll get this reviewed, good work and thank you!

Thank you! Just fixed some issues I noticed with the tooltip, but should be good to review from my side now!

**Comment by jacobsfletch** [comment]
@AlessioGr I pulled this down and made a few of changes:
1. I swapped the `a` tag with `next/link` to enable in-app navigation. Users can easily open in new tab with a command+click or right-click as expected.
1. The extra tooltip on the link was unnecessary so it was removed.
1. We lost the max-width and text-ellipse on the label. This is fixed.
1. When the field was cleared, the entire input field would shrink by 2px causing layout shift. This is fixed.
1. The "x" button was misaligned.

It feels pretty solid at this point but two things that need to be done yet are:
1. We need parity between the multi-select `relationship` and regular `select` fields. Basically update the `select` field to match what we've done here.
1. We also need to add an e2e test or two for relationships to avoid regression going forward. At least to ensure to ensure their drawers can open despite being `readOnly`.

I can hop back into this later to finish these up.

**Comment by jmikrut** [comment]
Hey @AlessioGr — I've jumped in here and caught up with the discussion. Unfortunately I feel like our UX is already becoming quite complicated within the Relationship field itself, and I don't want to create duplicity between the drawer UI and a link directly to the document. 

This may be good for power users, but the admin UI is used for significantly less tech-savvy users and they will quickly get overwhelmed by the amount of clickable areas / hotspots within a relationship pill.

Here's what we need to do:

- I think keeping the drag handle introduced into the input is great just to visually indicate the ability to drag 
- We should not restrict the drag area to be so small here though, as it requires a significant amount of mouse precision
- Instead of linking the name of the related item, we need to add a "Open in new tab" button within the Drawer UI itself that appears to the right of the "Editing ..."  headline. It should close the drawer and open the doc in a new tab. This will 100% require 2 clicks, but in our user testing with live marketing-type clients, they have reported the need for drawer UI and have never mentioned a "new-tab" button within the relationship field. 

What do you think?

**Comment by ToneseekerMusical** [comment]
@jmikrut as more of a power user and someone who regularly has 100+ tabs I'm working in, perhaps the linked name could be a user preference that needs to be opted into to allow us power users to still get the workflow benefits of being able to open the relationships in new tabs directly while also giving the marketing-type clients their preferred drawer UI by default? Just a thought.

**Comment by jacobsfletch** [comment]
@ToneseekerMusical I think we can still cater to power-users by enabling a cmd+click/right+click action on the label that opens directly in a new tab.

**Comment by AlessioGr** [comment]
> Instead of linking the name of the related item, we need to add a "Open in new tab" button within the Drawer UI itself that appears to the right of the "Editing ..." headline. It should close the drawer and open the doc in a new tab. This will 100% require 2 clicks, but in our user testing with live marketing-type clients, they have reported the need for drawer UI and have never mentioned a "new-tab" button within the relationship field.
> This may be good for power users, but the admin UI is used for significantly less tech-savvy users and they will quickly get overwhelmed by the amount of clickable areas / hotspots within a relationship pill.

I think the optimal design would be to make it perfect for both power-users and non-techy users. Having it only inside of the drawer is.. eh. Now 

> I think we can still cater to power-users by enabling a cmd+click/right+click action on the label that opens directly in a new tab.
I think that's a nice solution! Maybe even add a bigger tooltip which mentions the keybind for that. Drawers cannot be opened in new tabs anyways, so this would work!

**Comment by jacobsfletch** [comment]
A tooltip is overkill imo, power-users by definition will know of hidden features, especially if they're well documented and discussed. If it's _really_ an issue, the bigger UX picture here is some sort of user-onboarding journey or deliberately designed "tips and tricks" feature—both outside the scope of this PR but something to consider.

To recap, this PR can still provide value in two ways:
1. Add a drag icon to sortable select fields as visual indication of the sorting feature. This change would mean that sortable selects will appear visually different than select fields that are not sortable, so we need to confirm that this design pattern is acceptable.
1. Add click-action to each selected option to bypass the drawer from opening, and instead directly navigate to the document.

**Comment by jacobsfletch** [comment]
Hey @AlessioGr! This PR was partially resolved in #1989. Then to follow up on the drag handle idea, this is likely _not_ a pattern we are going to adopt, at least not without thorough design—#1865 has some conversation around the same thing. This PR can still provide some value, though, which is to enable some sort of direct link to related documents, bypassing the drawer. As discussed the best solution here might be to enable keyboard shortcuts, like command+click or similar. I'm going to close this PR out, feel free to open a fresh PR if you want to continue to explore this idea!

**Pull request closed without merging**
