### PR TITLE
fix: Rich Text link respect enableRichTextRelationship

### PR DESCRIPTION
**Pull request by mvarendorff2**
## Description

`collection.admin.enableRichTextRelationship` allows hiding collections in the selection of the Rich Text's relationship drawer. This configuration is not respected by the link button however. This PR aims to fix that by filtering the collections in the same way the relationship button already does.

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DanRibbens** [comment]
I would add an additional property for this since it is a separate concern. I've been discussing this exact thing https://github.com/payloadcms/payload/discussions/2567.

What do you think?

**Comment by mvarendorff** [comment]
If you think that makes more sense, I don't mind that! It was just an inconsistency that came up in a recent usecase for one of our projects and using the same boolean that is also used for the relationships (since it's just a relationship field either way) seemed like the most straightforward way.

Sooooo, `enableRichTextLink` then? @DanRibbens

**Comment by DanRibbens** [comment]
Hey @mvarendorff, thanks for being flexible. We do want to split the flag to do links separately from the relationships for RichTexts.

**Comment by mvarendorff** [comment]
Alright, that's fair! I updated everything, let me know if something is missing :)

**Comment by DanRibbens** [comment]
Looks great! Thank you @mvarendorff!

**Pull request merged**
