### PR TITLE
feat: Add an OpenAPI specification endpoint

### PR DESCRIPTION
**Pull request by janbuchar**
## Description

Discussed in #1780 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Teyras** [comment]
@jacobsfletch So far, I managed to almost fully document the REST API for collections. Before I proceed, I have a couple of questions.

- Does the project use any automatic formatting tool? If not, what is the preferred code style?
- What kind of tests do you expect this to have? Does simply invoking the specification endpoint suffice? I believe that comparing the result to a predefined specification would not be very helpful. Maybe invoking a 3rd party validator on the result would be enough.
- Where in the docs should I mention this?

**Comment by jacobsfletch** [comment]
@Teyras this is amazing!! At first glance it's looking great. After seeing the code though I do think this would be better suited as a plugin. This is all achievable in a plugin format, everything from opening the endpoint and handling the operation. As a plugin, your going to have a lot more freedom to ship new ideas (like whether to support OpenAPI 3.0 or 3.1). This also makes your tests and docs are entirely independent of Payload. What do you think about this?

**Comment by jacobsfletch** [comment]
> I'm open to the idea, but I believe I'd still need the changes from https://github.com/payloadcms/payload/commit/252922c62d25337b3247e28cfce10ae6ff08e1fe (I don't think the code needs to be in an openapi.ts file though - pretty much anything importable from the module works).

Yep this makes sense. By the looks of it that change is not specific to OpenAPI, you just need an abstracted `entityToJSONSchema` function to use. In that case we could make that change to Payload core as needed.

For custom endpoints, we'd just require the hard-coded schema for each endpoint to be passed through the plugin.

**Comment by Teyras** [comment]
> > I'm open to the idea, but I believe I'd still need the changes from [252922c](https://github.com/payloadcms/payload/commit/252922c62d25337b3247e28cfce10ae6ff08e1fe) (I don't think the code needs to be in an openapi.ts file though - pretty much anything importable from the module works).
> 
> Yep this makes sense. By the looks of it that change is not specific to OpenAPI, you just need an abstracted `entityToJSONSchema` function to use. In that case we could make that change to Payload core as needed.

Perfect, if you tell me an appropriate location for that function, I can make a PR.

> For custom endpoints, we'd just require the hard-coded schema for each endpoint to be passed through the plugin.

Exactly - that sounds a fair bit less convenient than colocating the hard-coded schema with the registration of the custom endpoint.

**Comment by jacobsfletch** [comment]
> that sounds a fair bit less convenient than colocating the hard-coded schema with the registration of the custom endpoint.

I think you _could_ generate some generic API schema by reading the `endpoints` config, but I don't think there'd be a way to describe those custom endpoints well enough solely based on their config.

**Comment by Teyras** [comment]
> > that sounds a fair bit less convenient than colocating the hard-coded schema with the registration of the custom endpoint.
> 
> I think you _could_ generate some generic API schema by reading the `endpoints` config, but I don't think there'd be a way to describe those custom endpoints well enough solely based on their config.

Yes, that could be a good way to remind plugin users to document their custom endpoints.

How about the module for `entityToJSONSchema`, where should I move it?

**Pull request closed without merging**
