### PR TITLE
feat: every-operator

### PR DESCRIPTION
**Pull request by foopis23**
## Description
I was trying to create a query that selects docs if all elements of a relationship multi-select were in another list. I wanted to do this because I wanted to write an access control function that only allows users to edit posts where all the tags on the post are in the user's "editable tags" fields. I wrote a little more about it in this discussion post  https://github.com/payloadcms/payload/discussions/1751.

To do this kind of queries, I ended up adding operators for `every_equals`, `every_not_equals`, `every_in`, `every_not_in`. They work exactly like expected. If every element in a multi select or multi relationship equals or is in, etc. then it matches the document. One counter intuitive thing about that is that, all documents where the array is empty match. This is because in that case none of the element don't match the criteria, because there are no elements to false to. It's possible to change this by adding something like `$or: [{$not: {$size: 0}}]`, but I figured that is beyond the scope of this feature and limits the use of the every operators. It would be more helpful if a `size` and `not_size` operators were also implemented for users that want to not match empty arrays.

My implementation was to change the operator map in the build query section of the code to support arrays. When building the query, it puts each element into in object as a key and sets that object to the value of the last key. If it's the final key, then it sets the value equal to what was passed into the query.

For example, lets look at the every_in operator

**Operator Map**
``` 
{
    ...
    every_in: ['$not', '$elemMatch', '$nin']
    ...
}
```

**Payload Query**
```
{
    where: {
        multiSelect: {
            every_in: ["1", "2"]
        }
    }
}
```

**Output Mongodb Query**
```
{
    multiSelect: {
        $not: {
            $elemMatch: {
                $nin: ["1", "2"]
            }
        }
    }
}
```

After that it was as simple as hooking up types and operator lists to make sure that the operators actually ran the proper code paths and compiled. 

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jmikrut** [comment]
This is amazing.

We are going to pull it down today and review but after a cursory pass at the PR, it looks great!

Thank you! More from us soon.

**Comment by JarrodMFlesch** [comment]
Hey @foopis23 I attempted to merge your changes with master but I was unable to push the changes back to your branch. If you could update to align with master that would be great and then we can finally get this merged in. 

Here is a branch I pushed my changes to since I was unable to push back up to yours.
[foopis23-feature](https://github.com/payloadcms/payload/compare/foopis23-feature/every-operator?expand=1)

**Comment by DanRibbens** [comment]
We typically squash changes when we merge pull requests so rebaseing isn't necessary. Do whatever is easiest for you.

Let us know if you get stuck on the failed test.

Thanks!

**Comment by foopis23** [comment]
I feel like this can't be right. I ended up merging in [foopis23-feature](https://github.com/payloadcms/payload/compare/foopis23-feature/every-operator?expand=1) into my branch. All the tests seemed to be working and my feature was still in. So I pushed and now it says that there are thousands of file changes... I may need some help.  I have experience with git, but not a ton of experience with git projects of this size.

**Comment by foopis23** [comment]
As far as I can tell, that checkbox was already checked. If it wasn't, it is now.

Screenshot 2023-06-05 at 8 26 19 PM

I'm taking a look at the failing tests now. 

Also, I think you are right about the all operator. I'm double-checking it, but it seems like every_in is redundant. If that is the case, we could get rid of the every_in operator and rename the other operators to be more consistent with the all operator. (`none`, `all_equal`, `none_equal`)?

**Comment by JarrodMFlesch** [comment]
Ok yes, that is a very helpful example! I guess I am just hung up on the naming still. I thought about it for a while yesterday and still could not come up with a good naming convention. I was leaning towards `in_exclusive` but still, not sure how I feel about it.

**Comment by foopis23** [comment]
Yeah, I'm open to renaming them, but I haven't be able to come up with a better name. I do think `every_in` makes more sense, to me personally, than `in_exclusive`. I think its because I think of this query operators going left to right (`document.field every_in specified value`). In english I think I would say, every element of document.field is in the specific value. Sort of similar to `document.field < specified value`. 

Another comparison to make is that its like the .every operator in javascript. Maybe to clue users in even more we could call it `every_includes` so that is more like the javascript operator names? Although, I don't love that name either. 
```js
const documentField = [1];
const specifiedValue = [1, 2, 3];
documentField.every(value => specifiedValue.includes(value))
```

**Comment by qgwr32** [comment]
> The every_in operator selects the documents where the value of the field is an array where every value is in the specific elements.

That sounds like a subset. The operator returns true, if the documents array field is a subset of a given set.
I'm not sure if `is_subset` is generally less ambiguous than `every_in`, although it is for me.

**Comment by denolfe** [comment]
Hey @foopis23, this would still be a great addition to Payload. We've recently migrated our repository to a monorepo, which means in order for this PR to be viable, you'll need to update it to target the `main` branch and change the code to target `packages/payload`.

Let me know if this is something you can take on.

**Comment by denolfe** [comment]
Looks like this was superseded by #2740. Let's continue the conversation there.

**Pull request closed without merging**
