### PR TITLE
feat: supports RTL languages (2) - CSS

### PR DESCRIPTION
**Pull request by DasMergo**
## Description
related to : #2657
this will make directions to right for RTL support in CSS

Screenshot 2023-05-14 015023

- [x] I have read and understand the CONTRIBUTING.md document in this repository

### CODE REVIEW

**Comment by ibr-hin95** [comment]
@DasMergo  I think we were supposed to delete this pr, no? but @AlessioGr already started working on it, should I reapply the changes and start committing to this one instead? and is the base on [9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)? so that we can build on it?
I'm sorry to confuse you guys but @DasMergo  and I had a bit of issues coordinating between us

**Comment by AlessioGr** [comment]
> @DasMergo I think we were supposed to delete this pr, no? but @AlessioGr already started working on it, should I reapply the changes and start committing to this one instead? and is the base on [9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)? so that we can build on it? I'm sorry to confuse you guys but @DasMergo and I had a bit of issues coordinating between us

Oh what, you have a new PR?

**Comment by ibr-hin95** [comment]
> > @DasMergo I think we were supposed to delete this pr, no? but @AlessioGr already started working on it, should I reapply the changes and start committing to this one instead? and is the base on [9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)? so that we can build on it? I'm sorry to confuse you guys but @DasMergo and I had a bit of issues coordinating between us
> 
> Oh what, you have a new PR?
>
not really but we were supposed to delete this and start on a different branch on one of our forks so that we can coordinate properly and open a pr together but we haven't made a pr yet. so.. we can do whatever fits all, what do you think we should do?

**Comment by AlessioGr** [comment]
> > > @DasMergo I think we were supposed to delete this pr, no? but @AlessioGr already started working on it, should I reapply the changes and start committing to this one instead? and is the base on [9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)? so that we can build on it? I'm sorry to confuse you guys but @DasMergo and I had a bit of issues coordinating between us
> > 
> > 
> > Oh what, you have a new PR?
> 
> not really but we were supposed to delete this and start on a different branch on one of our forks so that we can coordinate properly and open a pr together but we haven't made a pr yet. so.. we can do whatever fits all, what do you think we should do?

Ohhh I see! So basically, I already merged your PR - this PR here is based on yours ([9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)). That should make it much easier to continue work on it - so let's keep working on this PR!

I also went ahead and fixed all of the obvious styling issues I've noticed. Could you check it out and let me know how it looks now?

**Comment by ibr-hin95** [comment]
> Ohhh I see! So basically, I already merged your PR - this PR here is based on yours ([9b098d8](https://github.com/payloadcms/payload/pull/2657/commits/9b098d8a959d1eab5c4de9c1d7bc712a21156fc4)). That should make it much easier to continue work on it - so let's keep working on this PR!
> 
> I also went ahead and fixed all of the obvious styling issues I've noticed. Could you check it out and let me know how it looks now?
>
yes I'll check it out and apply the changes here, but how should we coordinate between us? it's best to keep it in one pr but we should coordinate to avoid conflicts and avoid doing the same work twice

**Comment by ibr-hin95** [comment]
@AlessioGr 
so a few questions:
1. [fix: isFieldRTL detection](https://github.com/payloadcms/payload/pull/2660/commits/108bb472ed985fd64f53e3ddcd6420278cb9e566) : isn't this already included in the previous pr?
1. in the rest of the commits, I don't see checking for [dir=rtl], am I missing something here? 
The general guideline until now was to check for all styles that have (start/end/right/left) and group them under the rtl selector for overriding. I will commit a few changes as an example

**Comment by ibr-hin95** [comment]
Screenshot from 2023-06-06 03-13-36
@DasMergo @AlessioGr 
sorry for overwhelming you with the number of commits but I had to sync as many changes as I can since it's three people working on this.
the files in the pic are the files that I haven't reconciled yet, some because we both/three changed them, and some because I haven't had the time to test them (include test cases in my config). but I changed those files regardless and I need to reconcile the changes.
I'll have to leave it at that for today since I have to continue with my work, but I suggest we do the following:
1. we need to coordinate the work somehow
2. if you want I can commit all these files in one commit so that you can continue working on top of them, in that case, I only need to reconcile the conflicts, and you can test them.
3. if you want to work on other files and wait for me that's also possible but I haven't checked out how many changes still need to be done so I don't know how viable that is. especially since I'm working on this on a fairly random schedule so I don't know when I'll have time to continue
4. we need someone to keep track of the changes that need to be done and survey everything

**Comment by AlessioGr** [comment]
@ibr-hin95 
> [fix: isFieldRTL detection](https://github.com/payloadcms/payload/pull/2660/commits/108bb472ed985fd64f53e3ddcd6420278cb9e566) : isn't this already included in the previous pr?

Yep it is - I just noticed another issue with it, so I merged a fix for that in here as well.

> in the rest of the commits, I don't see checking for [dir=rtl], am I missing something here?
The general guideline until now was to check for all styles that have (start/end/right/left) and group them under the rtl selector for overriding. I will commit a few changes as an example

I've tried to minimize [dir=rtl] where I didn't need it. For example, in the block header, I just replaced all the margins used for left and right spacing with a `gap:` property, as gap works well on both rtl and ltr. This saves some extra CSS lines, so I'd say it's best to convert things to use `gap` where possible.

Also, didn't know you had unpushed changes here! I think it's best to commit & push any change directly, so everyone has the right version.
I've noticed a few times where the changes you've just committed "duplicated" some rules I added, e.g. the block header now has both a `gap`, and a `margin`.
I'll fix those up and then let you two work on it - just let me know when it's ready in that case :)
So, definitely do commit your other changes as well - just do check for conflicting `gap:` rules first

**Comment by DanRibbens** [comment]
I missed the chance to comment on #2657 before that was merged so I will give feedback here.

In PR #2657 we introduced a lot of code to handle the complexity of having the locale objects and support string only locales. I'd like to work on reducing the complexity instead of having to handle it everywhere.
How do we feel about sanitizing all locales from strings to full objects at start so that the code can be more simple throughout Payload?

I'd like to get rid of `unifiedLocaleConfig` and all the calls to it from so many places in the code and instead make it so that the SanitizedConfig only has the complete objects, with `label` and `value`.

This would likely be a breaking change for any custom components that expect locales to be a string. If that is the case we should consider this change for 2.0 or we could introduce another locale array in the sanitized config that contains the complete objects. I'm open to ideas here.

I considered a way of supporting both formats by adding a `toString` function, but this doesn't completely solve the issue, but I'll share it anyways incase we want to explore it more...
If the locale object was given `locale.toString = function () { return this.value; }` then you would be able to do things like `${locale}` and it would render correctly, but it wouldn't be completely non-breaking since if you did `locale === 'en'` the result would change.

Anyways, I'd like to see this made more simplified before it is merged and ready for release. If that means doing a 2.0, this is going to happen soon enough anyways with the database adapter work going on.

**Comment by AlessioGr** [comment]
@DasMergo @ibr-hin95 I've moved all of this into a feature branch: https://github.com/payloadcms/payload/tree/feat/rtl-support

Could one of you open a new PR targeting that feature branch **feat/rtl-support** (so not master or canary)? That way, we'll have one PR & branch both of you can contribute to. Will make coordination easier!

Will also let you handle work on the changes Dan has suggested, since you're doing amazing work on it already - but if you need any help, just let me know! ❤️

**Pull request merged**
