### PR TITLE
feat: add afterOperation hook

### PR DESCRIPTION
**Pull request by stefgootzen**
As discussed in the `core-dev` Discord channel [here](https://discord.com/channels/967097582721572934/1102950643259424828/1103704744100380762) previously, I've taken a go at implementing the `afterOperation` hook.

This hook allows users to manipulate the `docs` returned from the `find` operation. This functionality is different from the `afterRead` hook since that function will fire for every `doc` seperately, where this hook gives the user acces to all `docs`.

I do think the typing of the `AfterOperationHook` could be improved but I'm not sure how. Suggestions?

## Description

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
Hey @stefgootzen thanks for giving this a go! I think you are headed in the right direction here.

We should make sure that every occurrence of `.beforeOperation.reduce` has a counterpart `.afterOperation.reduce` in that file. It looks like you implemented it for the find operations but we need to implement it for all operations 👍

**Comment by stefgootzen** [comment]
Thinking about this some more I think this needs some discussion/thoughts: The `beforeOperation` hook exists so that "it can be used to modify the arguments that operations accept or execute side-effects that run before an operation begins.". 

Currently I've implemented the `afterOperation` hook so that it can be used to modify the documents that the operation returned or execute side-effects that run after an operation begins.

However, some operations do not return multiple documents like the `find` operation. For example, `findByID` returns just one `doc` and `forgotPassword` returns no `doc` or `docs` at all.

This means that the `AfterOperationHook` functions needs to change the type.

The current type is this:
```typescript
export type AfterOperationHook = (args: {
  args?: any;
  operation: HookOperationType;
  docs?: any[];
}) => any;
```

"Solution" version would be this. However I feel that it is quite annoying to use if the IDE (and developer) doesn't know if it returns a `doc` or `docs`. Any thoughts?
```typescript
export type AfterOperationHook = (args: {
  args?: any;
  operation: HookOperationType;
  docs?: any[];
  doc?: any;
}) => any;
```

**Review by DanRibbens — CHANGES_REQUESTED** [review]
Looks like good progress! Let me know what you think of the proposed changes.

**Comment by stefgootzen** [comment]
I've added the `afterOperation` hook to all the relevant operations. I've extracted it into a seperate function to avoid repeating. (Maybe in the future this can be done for other hooks as well).

`forgotPassword` is still throwing a type-error. Not sure how to fix this. One way could be to not re-assign `token` but I feel that would break consistency.

Also I still have to implement the _types_ and write some tests, however I'm not sure how to write the tests. The ones I've wrote now are not really the way to go I feel. Any suggestions?

**Comment by jacobsfletch** [comment]
@stefgootzen I went ahead and took a stab at improving types and tests on this, with types being exceptionally difficult. The types I have in place work 100% correctly within the Payload codebase but are receiving an incorrect `result` type in the `afterOperation` hook of my config [here](https://github.com/payloadcms/payload/pull/2697/files#diff-def1cfb321643a65087251d000af7093209fdc2604c6d3865150762cd5aaa164R12). From here we need to do two things:

1. Consolidate the operations and their return types. **_It's important we derive types from their original sources of truth_**, like I've started [here](https://github.com/payloadcms/payload/blob/e501e9959b9a2bf7fb7a65df57d8b799aba09d26/src/collections/operations/utils.ts). But my implementation fails to consolidate `find` and `findByID`, etc as needed.
1. Fix the config-level types for this hook. When we use conditional logic like `operation === 'update'` in your handler, for example, `result` should be properly typed to the update operation. This is crucial to the developer experience but probably not critical to this PR. There's got to be a way to achieve this, maybe using inferred types?

**Comment by jacobsfletch** [comment]
For anyone jumping into this thread, the difficult part of this PR is that this hook needs to correctly type `result` which is different depending on the operation that executed it. It could be aa document, paginated documents, or something different entirely.

**Comment by AlessioGr** [comment]
I've made significant improvements to the type annotations in our recent commits. Notably, for several operations, the result property now has enhanced typing through conditional logic. However, it's essential to highlight this:

Screenshot 2023-08-15 at 12 39 03@2x

Operations annotated with _todo_ currently lack proper typing for the `result` prop. This is primarily because these operations necessitate a Slug as a generic, in contrast to the others which require a document.

Unfortunately, within our hooks, we're bereft of access to TSlug. In fact, even the T Document isn't innately passed into the generic. To overcome this, I resorted to [type assertions](https://github.com/payloadcms/payload/pull/2697/files#diff-def1cfb321643a65087251d000af7093209fdc2604c6d3865150762cd5aaa164R60) to facilitate the required type suggestions.

This type challenge isn't exclusive to the afterOperation hook, but is pervasive across all hooks. Thus, I think this one is **ready to merge now** until we **fine-tune the typings in the future** by:

1. Merging [this PR](https://github.com/payloadcms/payload/pull/2851). This PR ensures that TSlug from the CollectionConfig is automatically cascaded down to its hooks, obviating the need for type assertions. **Due to breaking changes (due to type narrowing) we might have to wait until 3.0 for this one.**
2. Revisiting operations currently utilizing documents in lieu of Slugs as generics. We need to consistently employ Slugs or, alternatively, employ a conditional structure that seamlessly accommodates both Slugs and documents, fostering robust typings within the core tests as well.

**Comment by denolfe** [comment]
With the above comments, this all looks good to me 👍

**Pull request merged**
