### PR TITLE
chore(plugin-seo): add Ukrainian translations

### PR DESCRIPTION
**Pull request by BohdanK-W32**
## Description

Add Ukrainian translation to the Payload SEO plugin.
The following changes don't require any additional test suite or docs changes

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Chore (non-breaking change which does not add functionality)

## Checklist:

- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Review by jacobsfletch — APPROVED** [review]

**Comment by jacobsfletch** [comment]
Thanks @BohdanK-W32! We're also going to need to apply this change to the beta  as well to prevent regression. Would you be willing to open a second PR against the `beta` branch?

**Comment by BohdanK-W32** [comment]
@jacobsfletch, already did in https://github.com/payloadcms/payload/pull/5836

**Comment by jacobsfletch** [comment]
@BohdanK-W32 just noticing that the wrong key was used here. Should be `ua` and not `uk`. Details here: #5873

**Comment by jacobsfletch** [comment]
Another quick note, I do see that `ua` is actually a reference to the country code, not the language. This was a mistake introduced by the original author of that translation. But the above fix is still valid, since the `ua` key is already  in use. In 3.0 we should commit to `uk` or `ukr`, though, as suggested here: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes

**Comment by jacobsfletch** [comment]
Aaand just now seeing #5740

**Pull request merged**
