### PR TITLE
chore: update dependencies in website and ecom templates

### PR DESCRIPTION
**Pull request by JessRynkar**
## Description

#4363 

Updates our dependencies to fix errors thrown during `npm install`

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Chore (non-breaking change which does not add functionality)

### CODE REVIEW

**Comment by jacobsfletch** [comment]
The form builder plugin is installed in the website template but never used, so the only thing we might need to do here that is directly related to that issue is to remove that one dependency: #4385

**Comment by jacobsfletch** [comment]
I guess I should have just committed to this branch huh

**Comment by JessChowdhury** [comment]
Closing - will be fixed [here](https://github.com/payloadcms/payload/pull/4385).

**Comment by jacobsfletch** [comment]
One last note on bumping deps in package.json, if the version is identified using a caret `^` then patch and minor versions are will be automatically installed. Unless its pinned to a version, or there's been a major version change, or some sort of incompatibility/security, there's typically no need to update these.

**Pull request closed without merging**
