### PR TITLE
feat: support custom ids

### PR DESCRIPTION
**Pull request by jeanbmar**
## Description

This pull request aims to support custom ids in a way that:
- Developers can specify a custom id type when defining a collection
- Users can provide their own id values instead of the ones generated automatically by MongoDB

Related discussion: https://github.com/payloadcms/payload/discussions/262

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jeanbmar** [comment]
I'm initializing the PR for peer review. I'll communicate here when it's ready for a final review / merge.

**Comment by jeanbmar** [comment]
Custom ids are implemented using a new `id` property in the collection configuration.
Specifying `{ id: <Type> }` in a collection lets payload know that:
- The `id` field MongoDB is going to write in database should be of type `<Type>` (String, Number, etc.)
- `id` field value will be provided by user in admin or API when a record is created

Key elements of the solution:
- `_id` field is added to MongoDB schema when `id` is specified in collection (see https://mongoosejs.com/docs/guide.html#_id), to prevent automated id generation
- `ID` field is added to admin UI when a new record is being created when `id` is specified in collection
- `id` field is added to GraphQL creation mutation input type when `id` is specified in collection
- Restrictions on `ObjectId` type are loosen since `id` can now be of any MongoDB-compatible type
- Relationship schema building has been updated to support custom ids

**Comment by jeanbmar** [comment]
Update:
- Collections doc has been updated to reference the `id` property
- All existings tests are passing

I'm not sure about how to create additional tests though. I've noticed existing tests reference existing native collections but I can't use them.
Besides this, the PR is ready for review by Payload team.

**Comment by jmikrut** [comment]
@jeanbmar — this looks great! I just reviewed everything and have to hand it to you. Good work.

We should write some tests for this one though. What we'll probably want to do is inject a new collection config into the demo app, that _**does**_ use a custom ID, with which we can write some integration tests around to make sure that we can do the following functions (at a minimum):

- Allows document creation with custom ID
- Allows querying documents by custom ID (see your `buildQuery` changes)
- Allows `findByID` using a custom ID
- Allows setting relationship fields to collections with a custom ID, with all combinations of `hasMany` and many `relationTo`s

There are probably a few other test cases we should cover here but this list should get us started at least. 

Our team can handle writing these tests though. We have a big week this week, with a bunch of stuff coming out, but should be able to get to this shortly thereafter unless you are feeling up for it before then. What do you think?

**Comment by jeanbmar** [comment]
@jmikrut Thanks!

> One edge case I could see happening is that if a user specified that their ID was a `number`, instead of a string, GraphQL might freak out at the moment because it might expect a string to be passed as an ID. Not sure there - haven't tested it... just thinking out loud

I was wondering the same: as long as a string is passed to GraphQL (which is the case when using admin), Mongoose will cast the value to a Number afterward.

> Our team can handle writing these tests though. We have a big week this week, with a bunch of stuff coming out, but should be able to get to this shortly thereafter unless you are feeling up for it before then. What do you think?

That sounds great, thank you. I will run a fork in the meantime.

**Comment by DanRibbens** [comment]
> I was wondering the same: as long as a string is passed to GraphQL (which is the case when using admin), Mongoose will cast the value to a Number afterward.

I tested GraphQL for custom ids that are both String and Number. With Number I really didn't like how it expected a string so I made changes to allow that to happen. I also added all the tests. 

One outlier which isn't a big deal, but should probably be fixed is that we have id coming through as a field available in the data for update mutations. That really shouldn't be there given the id is immutable. This isn't really an issue with your PR as it has been there all along.

The only thing I haven't tested here is that you could have multiple types of IDs on one relation.  For example:

```js
const CustomID = {
  slug: 'custom-id',
  labels: {
    singular: 'CustomID',
    plural: 'CustomIDs',
  },
  id: Number,
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
  ],
};

const NormalID = {
  slug: 'normal-id',
  labels: {
    singular: 'NormalID',
    plural: 'NormalIDs',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
  ],
};

const Relations = {
  slug: 'relations',
  labels: {
    singular: 'Relation',
    plural: 'Relations',
  },
  fields: [
    {
      name: 'relations',
      type: 'relationship',
      relationTo: [ 'custom-id', 'normal-id' ],
    },
  ],
};
```

In the example `relations` is expected to have both types of IDs and I would like to see that this is possible before merging.

**Comment by DanRibbens** [comment]
Another thing to note that we could improve. 
If you have a Number id on a collection, the admin UI will allows text input that will error when saving and the message isn't very user friendly.
image

**Comment by jeanbmar** [comment]
> In the example `relations` is expected to have both types of IDs and I would like to see that this is possible before merging.

I think it's possible in the sense it won't crash, but we should maybe throw an error in this case. I can't find a valid use case where one would want to match ids of different types.

> Another thing to note that we could improve.
> If you have a Number id on a collection, the admin UI will allows text input that will error when saving and the message isn't very user friendly.

Indeed, I think it's the drawback of allowing any Mongoose schema type as collection id type.
We could probably tighten things on the id type by allowing only a subset of Mongoose types such as ObjectId, String and Number. We could then accordingly switch between `text` and `number` admin types for the ID field. What do you think?

**Comment by DanRibbens** [comment]
We literally just came to the same conclusion in our internal meeting this morning. I was planning to pivot the changes to do exactly this.

@jeanbmar Do you want to make the changes to lock it down to only `text` and `number` or should I?

Changes needed:
- Change id input to support either text (current) or number
- Add validation (might be fine without if the id input once input is corrected)
- schema validation in joi for collection `id` should only be strings of 'text' or 'number'
- cleanup code where possible (GraphQL switch case for types could be a simple `if`, etc.)
- update documentation

Am I missing anything?

Lastly, is the config name property `id` sufficient? It would be more semantic to rename it to `idType`, `idFieldType` or possibly something different?

**Comment by jeanbmar** [comment]
I'll give it a shot!

**Comment by jeanbmar** [comment]
I've pushed the discussed changes.
I see two additional things to check / consider:
1. Relationships id type consistency should be checked during sanitize calls. It could happen in something similar to the following way, but I wasn't sure about TS types so I didn't implement it: https://github.com/payloadcms/payload/blob/cb422bb4c6758607592127f1bc4e0d1a20378945/src/collections/config/sanitize.ts#L123-L124

2. We might want to change this as well, though it's purely visual:
https://github.com/payloadcms/payload/blob/cb422bb4c6758607592127f1bc4e0d1a20378945/src/admin/components/views/collections/List/formatFields.tsx#L11

**Comment by DanRibbens** [comment]
Your changes look good, thanks for taking that on.

I have one more thought about our approach and how this could be better yet.

Instead of having an independent property on the collection for the idType we could check in the actual collection fields for a field with `name: id` and let that be the replacement for auto-generating the id. 

By doing it this way some really cool possibilities are available like:
- change where the id input is shown
- Hide the id field and write a hook to set the id before save
- Use a custom components
- Add custom validation logic

We will have to validate the config to prevent localization for the id field. The id field can't be in a group. It must be required.

How do we feel about pivoting to making the id field work like all the fields? Any other potential issues?

 I can do some more work on this too.

**Comment by jeanbmar** [comment]
I agree, using an id field would make sense and enable additional capabilities now that the id type is either `text` or `number` instead of Mongoose types. I can spend some time on it today, let's a have a look.

**Comment by jeanbmar** [comment]
@DanRibbens I've pushed some changes as discussed, but I haven't handled the validation part. Could you take care of it?

**Comment by DanRibbens** [comment]
Yes, I'll review the changes and finish up anything missing when I'm free.

This will be great to get merged!

**Comment by jeanbmar** [comment]
I don’t have access to my device to commit myself at the moment, but I think this will need a change so the id is not included twice: https://github.com/payloadcms/payload/blob/53b119c0ca8d7b09e5f581f2aa3680cbd7ff7dc3/src/collections/graphql/init.ts#L112

**Comment by DanRibbens** [comment]
Ah, my bad. I had some trouble with git. I rebased changes from master and resolved conflicts, but then git push was being rejected even though I had all the commits in history from jeanbmar/payload:master. I thought if I pushed with -f it would be fine, I probably shouldn't have done that.

I've reopening the PR under a new branch: https://github.com/payloadcms/payload/pull/313

Lesson learned: don't let remote PRs get stale and be don't `-f`. Sorry for the confusion.

**Pull request closed without merging**
