### PR TITLE
fix: fixes more race conditions with transactions

### PR DESCRIPTION
**Pull request by diesieben07**
## Description

This pull request fixes two race conditions with transactions:

1. A [toc/tou issue](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) in `initTransaction`, which can lead two operations to both initialize a transaction and both think they are in charge of committing it.
2. A race condition in all operations that use `getEntityPolicies`. These operations did not start a transaction, and so the many operations that `getEntityPolicies` kicks off concurrently were racing for who starts and commits the transaction.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Review by DanRibbens — COMMENTED** [review]
From what I can tell this is exactly what we need having that req.transactionIDPromise. I would like to introduce a test suite called `database` under which we can add a some transaction specific int cases using just the local api that:
- multiple operations from one req async
- multiple operations from one req sync
- one successful operation, call another that fails and expect the rollback of the first operation

**Comment by diesieben07** [comment]
I will try to write a test suite that tests this, yes. I didn't do that yet, because I am not quite sure ho exactly to accomplish it. But I'll give it a shot tomorrow!

**Comment by DanRibbens** [comment]
Hey @diesieben07, I can probably sink a few mins in here and have it done. If you don't have this started, I can jump on it. Let me know!

**Comment by diesieben07** [comment]
@DanRibbens I appreciate the help, yes please go ahead! Unfortunately I did not have time to work on this yesterday and today and I'll be busy on the weekend, too.

**Comment by DanRibbens** [comment]
@diesieben07 Thank you so much for all the help with transaction stability!

**Pull request merged**
