### PR TITLE
Ability to get the "previous" state in the AfterChange Hook

### PR DESCRIPTION
**Pull request by AlessioGr**
## Description

Closes #941. Like the originalDoc object in beforeChange, each afterChange hook now has access to a `previousDoc` object. I hope the naming is fine – to me personally, it makes the most sense.

- [ X ] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by AlessioGr** [comment]
Also added `previousValue` to the afterChange hook, as this would further save time for developers.

**Comment by jmikrut** [comment]
@AlessioGr — this is great! I will be reviewing tomorrow. I think there may be a few tweaks necessary, but the naming, the typing, and overall everything, is looking amazing!

THANK YOU!

More from me shortly.

**Comment by AlessioGr** [comment]
> @AlessioGr — this is great! I will be reviewing tomorrow. I think there may be a few tweaks necessary, but the naming, the typing, and overall everything, is looking amazing!
> 
> THANK YOU!
> 
> More from me shortly.

Awesome, thank you! Let me know if there's anything which should be improved!

**Comment by denolfe** [comment]
Succeeded by #1115

**Pull request closed without merging**
