### PR TITLE
fix: rework build to not rely on initing payload

### LINKED ISSUE #3942: Build should not start payload (wasn't the case in v1)
### Link to reproduction

_No response_

### Describe the Bug

Within the CI setup to check if the build would work. Enviroment variables like this should not be used on build time, cause i and probably most others set the on runtime. Either those where temporary used in v1, but not validated or the behavoir changed.

```
 > press-lalique@1.0.0 build:payload
> payload build

[07:17:11] INFO (payload): Starting Payload...
/app/node_modules/payload/dist/email/build.js:33
        throw new _errors.InvalidConfiguration('Email fromName and fromAddress must be configured when transport is configured');
              ^

InvalidConfiguration: Email fromName and fromAddress must be configured when transport is configured
    at ensureConfigHasFrom (/app/node_modules/payload/dist/email/build.js:33:15)
    at buildEmail (/app/node_modules/payload/dist/email/build.js:68:9)
    at BasePayload.init (/app/node_modules/payload/dist/payload.js:226:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPayload (/app/node_modules/payload/dist/payload.js:259:26)
    at async initHTTP (/app/node_modules/payload/dist/initHTTP.js:39:21)
    at async Payload.init (/app/node_modules/payload/dist/index.js:27:25)
    at async build (/app/node_modules/payload/dist/bin/build.js:18:5) {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500
}
``

### To Reproduce

do not set env vars and run `npm run build` 

### Payload Version

2.0.14

### Adapters and Plugins

db-mongodb

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

Fixes https://github.com/payloadcms/payload/issues/3942

Moves the aliases from the db adapter packages into core. Removing the need to initialize before building.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by dominikzogg** [comment]
@JarrodMFlesch It seems your mocking some integrations on build, the problem i see with that, every extensions and other built it, like email (https://github.com/payloadcms/payload/issues/3942#issue-1969808189) would not be fixed that way. ENV vars should always be runtime, theirfor no ENV variables should be use on built time or only those related to a build, like DEV/PROD build.

**Comment by jmikrut** [comment]
@JarrodMFlesch we need to pick back up on this. Can we merge main and see what's left?

**Comment by JarrodMFlesch** [comment]
> @JarrodMFlesch It seems your mocking some integrations on build, the problem i see with that, every extensions and other built it, like email ([#3942 (comment)](https://github.com/payloadcms/payload/issues/3942#issue-1969808189)) would not be fixed that way. ENV vars should always be runtime, therefor no ENV variables should be use on built time or only those related to a build, like DEV/PROD build.

I believe this should work, as we are no longer `initing` payload on build so ENV's are not needed. ENV's with PAYLOAD_PUBLIC will appear in build, the rest will be their equivalent process.ENV.VARIABLE_NAME.

@jmikrut want to look this over? I tested by building a project locally with a built version of Payload with these changes.

**Comment by MarkKropf** [comment]
This appears to not be working.

On a vanilla install using the web template, during the payload build, config is undefined and the build fails. 

```bash
/payload/node_modules/.pnpm/payload@2.8.0_@types+react@18.0.21_typescript@4.9.5_webpack@5.89.0/node_modules/payload/dist/bin/build.js:21
    await _.default.config.admin.bundler.build(config);
                           ^

TypeError: Cannot read properties of undefined (reading 'admin')
    at build (/payload/node_modules/.pnpm/payload@2.8.0_@types+react@18.0.21_typescript@4.9.5_webpack@5.89.0/node_modules/payload/dist/bin/build.js:21:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.5.0
```

**Comment by paulpopus** [comment]
Hey @MarkKropf Thanks for you report, we're looking to fix this ASAP

**Comment by JarrodMFlesch** [comment]
@MarkKropf Thanks for reporting, I fixed this yesterday but never committed the change...? Just merged the fix in [this PR](https://github.com/payloadcms/payload/pull/4796), and we will release a new version ASAP.

**Comment by MarkKropf** [comment]
Thanks @paulpopus & @JarrodMFlesch  🙏

**Comment by MarkKropf** [comment]
I can confirm this now is resolved in the 2.8.1 tag. 

thanks again!

**Pull request merged**
