### PR TITLE
Fix: upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by wlaeri**
## Description

Running `yarn audit` identifies vulnerabilities in several dependencies:
```
yarn audit v1.22.18
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > got                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1080920                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > update-notifier > latest-version > package-json │
│               │ > got                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1080920                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Authorization Bypass in parse-path                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ parse-path                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > git-url-parse > git-up > parse-url > parse-path │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1081004                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ parse-url parses http URLs incorrectly, making it vulnerable │
│               │ to host name spoofing                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ parse-url                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=8.1.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > git-url-parse > git-up > parse-url              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1084485                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Server-Side Request Forgery (SSRF) in GitHub repository      │
│               │ ionicabizau/parse-url                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ parse-url                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=8.1.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > git-url-parse > git-up > parse-url              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1084488                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ sharp vulnerable to Command Injection in post-installation   │
│               │ over build environment                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sharp                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.30.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ sharp                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ sharp                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1084442                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ vm2 vulnerable to Sandbox Escape resulting in Remote Code    │
│               │ Execution on host                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ vm2                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.9.11                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ release-it                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ release-it > proxy-agent > pac-proxy-agent > pac-resolver >  │
│               │ degenerator > vm2                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1084591                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
7 vulnerabilities found - Packages audited: 1947
Severity: 4 Moderate | 1 High | 2 Critical
```

Upgrading `sharp` and `release-it` fixes all of these vulnerabilities.

```
yarn audit v1.22.18
0 vulnerabilities found - Packages audited: 1995
```

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jmikrut** [comment]
Hey @wlaeri - thank you for doing this! 

Did you mean to specify Node and Yarn versions? I would like to remove those specifications, as that means we will drop support for Node 14, etc. And I think that we should still be able to support Node 14.

Is this a requirement of using the newer `release-it` and / or `sharp` dependencies?

**Comment by wlaeri** [comment]
Good question @jmikrut. Node 16 is not a requirement of the newer dependencies, but I thought I'd specify Node and Yarn versions in the `package.json` and `.node-version` file since I didn't see them specified. I removed them for this PR, but happy to open a new PR if you want them back in. I can specifying `>=14` for node in the engines block if you want to support Node 14 as well. Let me know.

**Comment by wlaeri** [comment]
Hey @jmikrut, I moved the Node and Yarn version specification to [this PR](https://github.com/payloadcms/payload/pull/1240) and fixed the issue with merge conflicts. Let me know if there is anything else I can do.

**Comment by jmikrut** [comment]
Hey @wlaeri - this looks great. Can you merge master and resolve the conflicts in `yarn.lock`? After that, I'll merge!

**Comment by wlaeri** [comment]
Hey @jmikrut just merged up master and resolved the conflicts in `yarn.lock`. Let me know what else I can do!

**Comment by jmikrut** [comment]
@wlaeri — thank you so much! This is great.

**Pull request merged**
