### PR TITLE
Allow Expiration of Collection Documents

### PR DESCRIPTION
**Pull request by gkemp94**
## Description

This minor change adds the ability to define an expiration TTL on a date field. It's a supported mongoose option, and would allow the building of more complex apps. I'll be using this to build a cart like functionality where stale shopping carts can be removed to ensure that it does not get out of control. Couldn't figure out how to do this with plugins so made this quick change. 

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jmikrut** [comment]
Hey @gkemp94 — very interesting. My only hesitation here is that if we decide to support other databases down the line, this functionality is probably quite specific to Mongo and would not be able to be replicated within other DBs. 

This almost feels like something that a `cron` job could do—where you'd store an indexed date of when the cart is created, and then periodically you have a `cron` job run that queries for any carts older than X seconds. Then you'd delete each cart that gets matched. It wouldn't be a _**plugin**_, per se, because it's pretty specific to your app's logic, but it could be done that way nonetheless.

What do you think about that approach? 

Alternatively, I'd like to get with the Payload team to look into how we could support something like this in MySQL / Postgres to future proof ourselves a bit here. 

If we're looking like we can support a similar function with those databases, then I've only got a few points of feedback for this PR and we can move forward from there. 

Let us get back to you shortly!

**Comment by gkemp94** [comment]
@jmikrut, thanks for the review. Totally understand that if the roadmap contains additional database support, then this PR would most likely not be the best option. If I understand the stack currently, there isn't a way to generate CRON jobs within payload CMS, correct? And would need to be queued up by another service. That's totally a viable option, if this PR doesn't make sense for the roadmap of payload, I'm happy to go down that route instead.

**Comment by denolfe** [comment]
@gkemp94 We do a database reset/seed on a cron job in our public-demo repo. It is all done outside of Payload but leverages the Payload's local API. Here is where it is done, so you can take a look: https://github.com/payloadcms/public-demo/blob/master/src/cron/reset.ts

**Comment by DanRibbens** [comment]
I personally cringe at the idea of managing cron jobs for data operations in production apps. 

What if instead of deleting stale carts your implemenation filters the it with a `where` query. This way the cart data is never deleted in your db which could be of analytical and marketing value later on. 

Obviously you know your app needs better than I can speculate, but that is where my head for whatever it is worth.

```js
const today = new Date();
payload.find({
  collection: 'carts',
  limit: 1,
  where: {
   and: [
     user: { equals: userID },
     updatedAt: { less_than: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7),
   ]
  },
);
```

**Comment by DanRibbens** [comment]
Given the discussions above, this feature is very project specific and has some good alternatives so I'm closing it. I'm happy to discuss more on this if it comes up again.

**Pull request closed without merging**
