### PR TITLE
feat(storage-vercel-blob): threads cacheControlMaxAge through static handler

### PR DESCRIPTION
**Pull request by wellitongervickas**
## Description
I'm facing a issue while trying to set a cache age for vercel blob storage plugin, this way I changed to accept and set as response the cache control.

### Before changes
image
image

### After changes

image

image

### Using plugin
```
vercelBlobStorage({
      enabled: true, // Optional, defaults to true
      // dev: Specify which collections should use Vercel Blob
      collections: {
        [Media.slug]: true,
      },
      // dev:Token provided by Vercel once Blob storage is added to your Vercel project
      token: process.env.BLOB_READ_WRITE_TOKEN!,
      cacheControlMaxAge: 31536000, /// the same we see
    }),
```

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by wellitongervickas** [comment]
image
Example working with this change, now getting from disk cache

**Comment by arthurmr96** [comment]
👍

**Review by jacobsfletch — APPROVED** [review]

**Comment by denolfe** [comment]
We may want to allow customizing this at a _per-collection_ level in the future.

**Comment by wellitongervickas** [comment]
thanks, it will improve a lot my projects

**Pull request merged**
