### PR TITLE
fix(ui): populate default values in join related doc drawer

### LINKED ISSUE #8612: defaultValue is ignored when creating a doc from "Add new" on a join field.
### Link to reproduction

_No response_

### Environment Info

  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.111
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.111
  @payloadcms/graphql: 3.0.0-beta.111
  @payloadcms/next/utilities: 3.0.0-beta.111
  @payloadcms/richtext-lexical: 3.0.0-beta.111
  @payloadcms/translations: 3.0.0-beta.111
  @payloadcms/ui/shared: 3.0.0-beta.111
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926

### Describe the Bug

defaultValue setting appears to not work when generating a new doc from a join field.

### Reproduction Steps

Set a defaultValue on a collection -> Test by creating a new item -> Try creating a new item from a join field ("Add New" or "Create New <collectionName>" button), field will be blank.

### Adapters and Plugins

db-mongodb

### PR DESCRIPTION
**Pull request by akhrarovsaid**
fixes #8612

I'm not convinced this was the cleanest way to solve this issue, however all other methods I tried induced an error in the form state builder or required larger, more laborious code changes.

### CODE REVIEW

**Comment by akhrarovsaid** [comment]
As an aside: Before I began working on this fix, I occasionally received `ERROR: Could not find field schema for given path "undefined"` errors somewhat sporadically while playing with the `Join` field. The errors triggered from clicking the `Create New` button and it was impossible to predict when they would happen. I can't seem to consistently reproduce these errors and they seem unrelated to this PR.

**Comment by DanRibbens** [comment]
> As an aside: Before I began working on this fix, I occasionally received `ERROR: Could not find field schema for given path "undefined"` errors somewhat sporadically while playing with the `Join` field. 

Probably need an optional chaining or early return in a hook during a render with missing props.

We have a few UI bugs with joins in our backlog. I hope to get some time this week for these.

**Comment by DanRibbens** [comment]
This is blocked until the [RSC refactor branch](https://github.com/payloadcms/payload/pull/8364) is complete. Thanks being patient, it's almost there.

**Comment by akhrarovsaid** [comment]
Hey @DanRibbens,

In my testing the join related document drawer form gets populated with the correct default values as of the on-demand RSC merge. I don't think this is relevant anymore so I'll be closing this, thanks!

**Comment by DanRibbens** [comment]
Thanks for testing @akhrarovsaid

**Pull request closed without merging**
