### PR TITLE
Feature for supporting hasMany property in text field

### PR DESCRIPTION
**Pull request by Gokulsck**
## Description

- Implemented a feature for handling hasMany property for text fields to store array of string.
- https://github.com/payloadcms/payload/discussions/4393
- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by DanRibbens — CHANGES_REQUESTED** [review]
This looks great so far, but I would like to see one e2e test if you're able to add it. Also I think it will fail for the postgres db adapter as we will need to handle that also. See how `number` is handled in this switch block? We will need similar for `text`: https://github.com/payloadcms/payload/blob/657d14c07b4c6da4f168a6b6853f932c44527639/packages/db-postgres/src/schema/traverseFields.ts#L146

**Comment by Cuzart** [comment]
I already worked on the same issue and I also reviewed your changes. I noticed that in the payload-types.ts the type for the hasMany, validateHasMany and so on is still `string | null` in my case it was set to `string [] | null` as I also included some changes in the "buildObjectType", "configToJSONSchema", and "buildMutationInputType". Maybe you want to have a look at my forked repo or give me access to work on the PR so I can also include those changes and the unit test I wrote @Gokulsck

**Comment by Gokulsck** [comment]
@Cuzart I gave you the access could you please check?

**Comment by Cuzart** [comment]
I handled the cases for the schemas similar to the ones found for number field with has many and fixed the type generation.
I changed some code in `validations.ts` which was causing an unit test to fail and also added one unit test and an e2e test for hasMany on text fields.  

The change for postgres seems pretty straightforward but you might consider renaming `hasLocalizedManyNumberField` to something more general to include the text field as well.

**Comment by Gokulsck** [comment]
> I already worked on the same issue and I also reviewed your changes. I noticed that in the payload-types.ts the type for the hasMany, validateHasMany and so on is still `string | null` in my case it was set to `string [] | null` as I also included some changes in the "buildObjectType", "configToJSONSchema", and "buildMutationInputType". Maybe you want to have a look at my forked repo or give me access to work on the PR so I can also include those changes and the unit test I wrote @Gokulsck

@Cuzart payload-types.ts is auto-generated not modified manually.

**Comment by Cuzart** [comment]
Sure, I know I did not manually modify it. I have run the generate-types script and modified the utility that is used to generate the file `configToJSONSchema` @Gokulsck

**Comment by Gokulsck** [comment]
> Sure, I know I did not manually modify it. I have run the generate-types script and modified the utility that is used to generate the file see `configToJSONSchema.ts` @Gokulsck

Ok. And the changes for Postgres db adapter is not very straightforward. Could you please check on that?

**Comment by Cuzart** [comment]
Yes you are right as I got more into it, it is not really straightforward. I am on it and got it working with postgres now but some tests are still failing so I have to do some more work here.

**Comment by Cuzart** [comment]
I tested it with postgres running locally all unit and e2e seem to run fine I guess that should be it and ready to be reviewed @DanRibbens . Hope I did not miss anything.

**Review by DanRibbens — APPROVED** [review]
It looks like you were able to have feature parity with hasMany text as we have with number, great job!
I might have tried to make some of the functions reusable between text and number, but that isn't super important.
Last thing, I've come to realize from reviewing this that for postgres, we are missing support for querying on hasMany text and number fields but that can be done later.

**Review by DanRibbens — APPROVED** [review]

**Comment by maxsynnott** [comment]
Just a note that it seems you guys have updated the docs before actually creating a new release with these changes. This caused me a bit of confusion when trying to use the `hasMany` option as currently documented [here](https://payloadcms.com/docs/fields/text)

**Pull request merged**
