### PR TITLE
feat: Improve admin dashboard accessibility

### PR DESCRIPTION
**Pull request by r3pwn**
## Description

In relation to discussion #1232 

This PR improves accessibility across the main Dashboard and Account pages, fixing issues like missing `aria-label` attributes, skipped heading levels (h5 directly underneath an h2), and an issue on the Account page where the language selector input was not properly associated with its label.

These changes are completely invisible to a typical visitor of the admin dashboard, and only aim to improve the navigability of the site when using a screen reader.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by jacobsfletch — APPROVED** [review]

**Comment by jacobsfletch** [comment]
@r3pwn this is amazing! Looking through the diff editor and it looks like you nailed it. Great work. We should be able to merge this in soon.

**Comment by r3pwn** [comment]
Good afternoon, @jacobsfletch! I pushed a small update to rebase on master (to resolve merge conflicts), and to fix the e2e tests.

**Comment by AlessioGr** [comment]
Hey @r3pwn,

this looks good to me, thank you a lot for the changes! We just found one single issue: when hovering over the checkbox's label, the hover style is missing:

https://github.com/payloadcms/payload/assets/70709113/7ff6e3bb-c2f5-4ca3-968a-4e8e4f646223

Could you fix this? Once this is addressed, we can get it merged!

**Comment by r3pwn** [comment]
@AlessioGr Sure, I think I should be able to get that done at some point later today

**Review by DanRibbens — APPROVED** [review]

**Pull request merged**
