### PR TITLE
chore: replaces current collapse icon

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
## Description

Adjusts the collapsible word/icon into a single icon format for desktop/mobile.

- [x] I have read and understand the [CONTRIBUTING.md](../CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Chore (non-breaking change which does not add functionality)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

#### Closed
CleanShot 2023-10-06 at 12 24 02

#### Open
CleanShot 2023-10-06 at 12 24 08

### CODE REVIEW

**Comment by jacobsfletch** [comment]
@JarrodMFlesch the hamburger icon should still be white, with the border only as gray.

**Comment by jacobsfletch** [comment]
@JarrodMFlesch the open state is misaligned to the left with the nav itself. Also noticing the size of the hamburger has gotten taller, it should stay as it used to be (shorter).

**Comment by JarrodMFlesch** [comment]
@jacobsfletch noted. I fixed the left alignment for all different screen sizes and reduced the icon line gap

CleanShot 2023-10-06 at 13 04 50
CleanShot 2023-10-06 at 13 04 55

**Comment by jacobsfletch** [comment]
Definitely better but the hamburger is still looking too tall. It should be a bit shorter than it is wide by like 4px. I typically do `top: 2px` and `bottom: 2px;` for the first and last lines to achieve this.

**Pull request merged**
