### PR TITLE
Run connectMongoose before starting payload init

### LINKED ISSUE #1795: Bug: Nodejs thread blocked by config validation causing mongoose timeout
# Bug Report

When using the app with a really big nested config, the validation process takes a long time (30s+) and blocks the Nodejs thread. This causes the mongoose connect function to time out because it is called asynchronously before the payload init function, but the connect function's async functions are never called due to the blocked thread. As a result, the server does not start.

I believe the validate function is the cause of this issue.

## Steps to Reproduce

1. Create a really really big, nested config
2. Try to start payload
3. Get a Mongodb timout

```sh
[20:21:19] INFO (payload): Starting Payload...
[20:22:10] INFO (payload): Payload Admin URL: http://localhost:3333/admin
[20:22:10] ERROR (payload): Error: cannot connect to MongoDB. Details: connection timed out
```

## Other Details

Tested with 1.1.26 and 1.4.1

Already Opened #1794

### PR DESCRIPTION
**Pull request by milamer**
## Description

Running and awaiting mongooseConnect before starting to initialize payload.

This will stop the bug that the mongoose connection times out while payload is still initializing.

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] Bug fix (breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

fixes #1795

### CODE REVIEW

**Comment by christian-reichart** [comment]
This bug caused a real headache for me, as suddenly my production ready website stopped working for no apparent reason. Really nice catch!

**Comment by milamer** [comment]
After further consideration, I believe that the fix for the initSync method should actually be placed in the initAsync method. Additionally, I think it may be beneficial to consider deprecating the initSync method altogether. What do you think about these suggestions?

**Comment by milamer** [comment]
Hi @jmikrut 

I hope you had a great holiday season and Happy New Year!

I added timings to the loadConfig function using performance.now and the results showed that the validate config step was causing the performance issue. Here are the timings:
```sh
require config took 920.4804660000373ms
validate config took 30935.8046439999ms
```

After switching to `initAsync`, the issue was resolved. I have updated this PR to revert the change to the `init` method and added a `@deprecated` doc string to it. I have also changed all instances of payload.init in the documentation to payload.initAsync and made the same change to all internal calls.

Let me know if you have any further thoughts on this.

**Comment by jmikrut** [comment]
Hey @milamer — you as well! It was a nice break but I was toying around with optimizing Payload's startup time the whole break anyway so not much rest :)

I am not sure about deprecating the `init` method. What if instead we will actually just make it async and use _**it**_ as the default way to initialize Payload? I figure ripping off the bandaid with a clear breaking change will be better than supporting `initAsync` _**and**_ `init`. 

What do you think?

This would be beneficial elsewhere as in the future we may transpile Payload's config 1 time on startup, rather than use tools like `swc/register`- and I imagine at some point those transpilation tools will _**require**_ us to move to `async` init anyway. Actually I know that ESBuild requires async as it is.

**Comment by milamer** [comment]
Hey @jmikrut, I understand your concerns about deprecating the init method. However, I wasn't sure if you would like a breaking change 😅. IMO you suggestion is the best solution. It's a clear breaking change, but it will likely be easier for users to understand and implement in the long run.

I've gone ahead and made those changes, reverting the previous changes, removing the init method, and renaming the initAsync method to init.

I'm not sure how to handle the examples in the server.js files either. I have made the changes to move the code after init into the onInit handler. However, an alternative solution would be to wrap the entire code in an async method to ensure compatibility with the new init method. What do you think would be the best approach?
```js
const express = require('express');
const payload = require('payload');

const app = express();

payload.init({
  secret: 'SECRET_KEY',
  mongoURL: 'mongodb://localhost/payload',
  express: app,
  onInit: () => {
    app.listen(3000, async () => {
      console.log('Express is now listening for incoming connections on port 3000.')
    });
  }
})

```

Let me know what you think.

**Comment by christian-reichart** [comment]
What do you guys think about keeping initAsync just as a caller function for init, and mark it as deprecated? That way, people who already use initAsync won't have an immediate breaking change.

**Comment by jmikrut** [comment]
@milamer I think your `server.js` solution is fine personally.

@christian-reichart I think personally if we're going to rip off a bandaid here, we just rip off the bandaid and keep things simple. I will do my best to write up a clear changelog including a breaking change, but I think this one is good to merge personally.

Gonna let it rip and we can go from there! THANK YOU everyone!

**Comment by jmikrut** [comment]
Hey @milamer and @christian-reichart - unfortunately I have to roll back this PR before releasing the next patch version.

The team and I are definitely going to flatten the `init` method into one single asynchronous method, but we want to work it in with some other potential changes to how `init` works in general. 

We are working on some ways to allow Payload to be initialized for local use only, in as barebones of a way as possible which could be good for serverless cold-start times, etc. 

And the things that we may be changing as a result of this work might have impact on the `init` implementation, so I'd like to defer these changes until we know exactly what will come out of the final `init` architecture.

Does that make sense? I will keep this thread updated as we go. But for now, you can expect that this PR will be reverted until a later date, at which point you can just use `initAsync` to avoid the problems described above.

Thank you!!

**Pull request merged**
