### PR TITLE
feat: make textfields searchable in collections

### PR DESCRIPTION
**Pull request by christian-reichart**
## Description

Related Discussion: https://github.com/payloadcms/payload/discussions/974

With this feature developers can decide to include certain text fields in the full text search of a collection.
An example would be a field called 'tags', which is then easily searchable for content editors to filter their collection quickly.

Example collection config:
```
{
  slug: 'posts',
  fields: [
    {
      name: 'title',
      type: 'text',
    },
    {
      name: 'tags',
      type: 'text',
      admin: {
        description: 'Separate tags by space'
      },
    },
  ],
  admin: {
    useAsTitle: 'title',
    searchableTextFields: ['tags'],
  },
},
```

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by christian-reichart** [comment]
not sure where i should include tests for this one and how it could be tested efficiently. Any hints?

**Comment by DanRibbens** [comment]
This is some great work @christian-reichart, we are going to enhance this further with the following:

1. Write tests in /test/admin
2. enhance the search placeholder to include a human-friendly list of searchable field labels
3. Make sure it works with nested fields, within groups and relationships

We'll get these changes made for the next release shortly!

**Comment by christian-reichart** [comment]
@DanRibbens awesome. The placeholder is already extended.

Looks something like this:
`Search by Title, Field, Field, Field or Field`

**Comment by jmikrut** [comment]
Hey @christian-reichart — this was a great PR! We changed very little, besides renaming the new property to `listSearchableFields` instead to make it more specific, and removing the requirement that searchable fields are only text. You can now also search on any field that affects data.

I jacked up your PR on accident so I created a new PR (https://github.com/payloadcms/payload/pull/1116) but it is now merged and will be deployed to a new version shortly! THANK YOU!

**Comment by christian-reichart** [comment]
@jmikrut that's awesome to hear, glad I could contribute something!

Now it seems I have to create another PR to be listed as a contributor on GitHub. 🫠

**Comment by jmikrut** [comment]
@christian-reichart awwww man! Your commits did make it through to `master`, but I do see that it doesn't (yet) list you as a contributor. I thought it would. I did some Googling and found that sometimes it takes 24 hours for you to be listed as a contributor, so let's sit tight and see if we can get you to show up there. Otherwise, maybe you could make a small change to the docs in a new PR and then we will merge it right away. We wanna get you listed!

**Comment by christian-reichart** [comment]
@jmikrut no worries :D I'm sure I will come up with some advancement in the future since since we are going to use Payload productively.

**Pull request closed without merging**
