### PR TITLE
chore(payload/components): upgrade react-datepicker to v6

### PR DESCRIPTION
**Pull request by tyteen4a03**
## Description
 
Upgrades react-datepicker to v6.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by denolfe** [comment]
Looks like some unrelated (AWS) things are being updated in the pnpm-lock.yaml

**Comment by tyteen4a03** [comment]
> Looks like some unrelated (AWS) things are being updated in the pnpm-lock.yaml

Odd, l'll have a look!

**Comment by tyteen4a03** [comment]
> Looks like some unrelated (AWS) things are being updated in the pnpm-lock.yaml

Fixed, sorry about that!

**Comment by AlessioGr** [comment]
Thank you for your PR! In the process of getting react-datepicker to work on 3.0 (the `alpha` branch), I have already updated it to the latest version, so I'll be closing this here.

**Pull request closed without merging**
