### PR TITLE
fix(db-postgres): add `ON DELETE CASCADE` to foreign key constraint of select hasMany relationship

### LINKED ISSUE #6485: Unable to delete record from admin in postgres if collection has array field type
### Link to reproduction

_No response_

### Describe the Bug

I am using the postgresdb adapter. and update the Users collection with following additional field:

```
        {
            name: 'roles', // required
            type: 'select', // required
            hasMany: true,
            admin: {
                isClearable: true,
                isSortable: true, // use mouse to drag and drop different values, and sort them according to your choice
            },
            options: [
                {
                    label: 'Super Admin',
                    value: 'superadmin',
                },
                {
                    label: 'Owner',
                    value: 'owner',
                },
                {
                    label: 'Admin',
                    value: 'admin',
                },
                {
                    label: 'Instructor',
                    value: 'instructor',
                }
            ],
        },
```
        
        I can save the document successfully and I notice payload create an additional table user_roles to track that. When I try to delete the record from admin. It looks like the user_roles record are not removed first nor the cascade delete is executed when delete from user. That cause the fk_constraint error in user_roles table which block the delete operation.

I noticed there are some discussion about cascade in relationship but there is no conclusion there. I want to know if there are some existing workaround for that using hook but I am not able to find such information in the documentation as well.

### To Reproduce

Create a new project using the default user schema.
Modify Users.ts with additional field

```
   fields: [
        {
            name: 'roles', // required
            type: 'select', // required
            hasMany: true,
            admin: {
                isClearable: true,
                isSortable: true, // use mouse to drag and drop different values, and sort them according to your choice
            },
            options: [
                {
                    label: 'Super Admin',
                    value: 'superadmin',
                },
                {
                    label: 'Owner',
                    value: 'owner',
                },
                {
                    label: 'Admin',
                    value: 'admin',
                },
                {
                    label: 'Instructor',
                    value: 'instructor',
                },
                {
                    label: 'Student',
                    value: 'student',
                },
                {
                    label: 'VIP',
                    value: 'vip',
                },
            ],
        },
    ],
```

Create a user through the payload cms admin page.
Try delete the user through the payload cms admin page and error toast occured.

### Payload Version

2.18.3

### Adapters and Plugins

db-postgres

### PR DESCRIPTION
**Pull request by ikenox**
## Description

This PR fixes https://github.com/payloadcms/payload/issues/6485.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes

### CODE REVIEW

**Comment by ikenox** [comment]
Hi @DanRibbens ,
This bug seems critical and easy to fix. Cloud you review this PR?
I know payload team is working hard for v3, thanks.

**Review by DanRibbens — APPROVED** [review]
Thanks for the PR!

**Comment by DanRibbens** [comment]
Thank you for the nudge on this @ikenox. Once the tests pass we'll get merged.

**Comment by ikenox** [comment]
@DanRibbens 
Thank you for your immediate response!

[The failing test](https://github.com/payloadcms/payload/actions/runs/9477372764/job/26362574364?pr=6735) says the following.

```
  MongoServerError: WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.

        at Connection.onMessage (/home/runner/work/payload/payload/node_modules/.pnpm/mongodb@4.17.1/node_modules/mongodb/src/cmap/connection.ts:449:20)
        at MessageStream.<anonymous> (/home/runner/work/payload/payload/node_modules/.pnpm/mongodb@4.17.1/node_modules/mongodb/src/cmap/connection.ts:241:56)
        at processIncomingData (/home/runner/work/payload/payload/node_modules/.pnpm/mongodb@4.17.1/node_modules/mongodb/src/cmap/message_stream.ts:188:12)
        at MessageStream._write (/home/runner/work/payload/payload/node_modules/.pnpm/mongodb@4.17.1/node_modules/mongodb/src/cmap/message_stream.ts:69:5)
```

This error seems not to be related to the change of this pull request. The same error often occurs on main branch (e.g. [this commit](https://github.com/payloadcms/payload/actions/runs/9417604447/job/25943219207))

**Comment by DanRibbens** [comment]
This has already been done in `beta`, no additional PR needed.

Thanks for the contribution @ikenox!

**Pull request merged**
