### PR TITLE
feat: user preferences

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

In relation to: https://github.com/payloadcms/payload/discussions/174

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Ontopic** [comment]
Oehh, thanks :) was looking forward to this

**Comment by jmikrut** [comment]
@Ontopic hell yes. It's a big quality of life improvement. This PR as of now already saves column order and locale, but we're going to roll in the "collapsed" states of blocks on a document level (and maybe a few other items) before we merge.

Keep an eye out! What do you think of the approach?

**Comment by Ontopic** [comment]
Overwhelmed with your push for the next episode as well. Gonna carefully take a look and document my experiences and questions here, but it's definitely all looking like the kind of quality I'm starting to get almost used to 🙃

**Comment by Ontopic** [comment]
No bugs so far 😅 Everything running like I expected it to. I feel there's a lot of extra opportunities within this setup - like most of the stuff you guys create - waiting to be explored. To prevent myself forking or monkey-patching stuff that could be done cleanly, some extra guidelines and insights into how to approach certain tasks would be a nice addition :)

**Pull request merged**
